"""Algorithm metadata: one record per algorithm (sections 11, 47, 48).

Drives the Algorithm Explorer filters, the Algorithm Selector, the
"algorithm profile" panel on every algorithm page (the textual items of the
27-point template), docs/algorithm_matrix.md and tests.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Algorithm:
    id: str
    name: str
    module: str                 # curriculum module id
    estimator: str              # main library class
    tasks: tuple[str, ...]      # "regression" | "classification" | "clustering" | "dimred" | "anomaly"
    supervised: bool
    linear: bool
    parametric: bool
    scaling: str                # "required" | "recommended" | "not needed"
    categorical_native: bool
    missing_native: bool
    interpretability: str       # "high" | "medium" | "low"
    probabilistic: bool         # calibrated-ish probabilities out of the box
    online: bool                # partial_fit / incremental
    ensemble: bool
    problem: str
    intuition: str
    learned: str
    assumptions: str
    preprocessing: str
    categorical: str
    missing: str
    complexity: str
    strengths: tuple[str, ...]
    weaknesses: tuple[str, ...]
    failure_modes: tuple[str, ...]
    diagnostics: tuple[str, ...]
    interpretation: str
    references: tuple[str, ...] = ()


_A = Algorithm

ALGORITHMS: tuple[Algorithm, ...] = (
    _A("linear_regression", "Linear Regression (OLS)", "linear_regression", "sklearn.linear_model.LinearRegression",
       ("regression",), True, True, True, "not needed", False, False, "high", False, False, False,
       "التنبؤ بهدف عددي كتركيبة خطية من الخصائص.",
       "أفضل مستوى (Hyperplane) يمر عبر سحابة النقاط بحيث يكون مجموع مربعات المسافات العمودية على y أصغر ما يمكن.",
       "المعاملات β والحد الثابت (coef_, intercept_).",
       "للتنبؤ: علاقة قريبة من الخطية بعد التحويلات. للاستدلال: خطية، استقلال، تجانس التباين، عدم تعدد خطي تام، (طبيعية البواقي للعينات الصغيرة).",
       "ترميز الفئات، تعويض المفقود، تحويل المتغيرات الملتوية حين يلزم.",
       "One-hot (مع حذف فئة مرجعية للاستدلال).", "لا يدعم NaN؛ عوّض داخل Pipeline.",
       "تدريب O(np² + p³)، تنبؤ O(p).",
       ("سريع وقابل للتفسير", "حل مغلق فريد", "أساس لفهم كل ما بعده"),
       ("لا يلتقط اللاخطية دون خصائص مصممة", "حساس للقيم الشاذة", "غير مستقر مع التعدد الخطي"),
       ("تعدد خطي ⇒ معاملات متقلبة وإشارات مقلوبة", "قيمة شاذة مؤثرة تسحب الخط", "استقراء خارج مدى البيانات"),
       ("Residuals vs fitted", "Q-Q plot للبواقي", "VIF", "Leverage وCook's distance"),
       "β_j = التغير المتوقع في y لزيادة x_j وحدة واحدة مع تثبيت الباقي — ارتباط شرطي، لا أثر سببي إلا بافتراضات إضافية.",
       ("Hastie, Tibshirani & Friedman (2009), ESL, ch. 3",)),
    _A("ridge", "Ridge Regression", "regularization", "sklearn.linear_model.Ridge", ("regression",), True, True, True,
       "required", False, False, "high", False, False, False,
       "انحدار خطي مستقر حين تكون الخصائص كثيرة أو مترابطة.",
       "نضيف «ثمنًا» لحجم المعاملات فينكمش كل معامل نحو الصفر دون أن يصبح صفرًا.",
       "المعاملات المنكمشة.", "كالانحدار الخطي، مع قبول تحيز صغير مقابل تباين أقل.",
       "القياس إلزامي لأن العقوبة تعتمد على مقياس كل خاصية.", "One-hot.", "لا يدعم NaN.",
       "مثل OLS؛ RidgeCV يستفيد من LOO فعّال.",
       ("يعالج التعدد الخطي", "حل مغلق", "ممتاز حين p كبير ومعظم الخصائص مفيدة قليلًا"),
       ("لا ينتج ندرة", "يحتاج اختيار alpha"), ("نسيان القياس ⇒ عقوبة غير متوازنة",),
       ("Coefficient path", "Validation curve على alpha"),
       "المعاملات متحيزة نحو الصفر: لا تفسرها كأثر غير متحيز.",
       ("Hoerl & Kennard (1970), doi:10.1080/00401706.1970.10488634",)),
    _A("lasso", "Lasso", "regularization", "sklearn.linear_model.Lasso", ("regression",), True, True, True, "required",
       False, False, "high", False, False, False,
       "انحدار خطي مع اختيار تلقائي للخصائص.",
       "قيد L1 على شكل ماسة: زواياه على المحاور، فيلامس الحل المحور ⇒ معاملات صفرية بالضبط.",
       "معاملات متفرقة (كثير منها صفر).", "ندرة حقيقية تقريبية؛ خصائص غير شديدة الترابط لاختيار ثابت.",
       "القياس إلزامي.", "One-hot (قد يختار بعض فئات المتغير فقط).", "لا يدعم NaN.",
       "Coordinate descent: O(np) لكل دورة.",
       ("اختيار خصائص مدمج", "نماذج متفرقة سهلة النشر"), ("غير مستقر مع الخصائص المترابطة", "يختار ≤ n خاصية حين p > n"),
       ("اختيار عشوائي بين خصائص مترابطة", "استدلال ساذج بعد الاختيار (Post-selection inference)"),
       ("Coefficient path", "استقرار الاختيار عبر Bootstrap"),
       "صفر لا يعني «بلا علاقة» بل «لم يُحتج إليها مع وجود البقية».",
       ("Tibshirani (1996), doi:10.1111/j.2517-6161.1996.tb02080.x",)),
    _A("elastic_net", "Elastic Net", "regularization", "sklearn.linear_model.ElasticNet", ("regression",), True, True,
       True, "required", False, False, "high", False, False, False,
       "الجمع بين ندرة Lasso واستقرار Ridge.", "عقوبة مختلطة تسمح باختيار مجموعات الخصائص المترابطة معًا.",
       "معاملات متفرقة ومستقرة.", "كـLasso/Ridge.", "القياس إلزامي.", "One-hot.", "لا يدعم NaN.", "كـLasso.",
       ("يختار المجموعات المترابطة معًا", "أكثر استقرارًا من Lasso"), ("معاملان للضبط (alpha, l1_ratio)",),
       ("ضبط غير كافٍ لـl1_ratio",), ("ElasticNetCV",), "كـLasso.",
       ("Zou & Hastie (2005), doi:10.1111/j.1467-9868.2005.00503.x",)),
    _A("huber", "Huber / Robust Regression", "robust_regression", "sklearn.linear_model.HuberRegressor", ("regression",),
       True, True, True, "recommended", False, False, "high", False, False, False,
       "انحدار خطي لا تجرّه القيم الشاذة في y.", "خسارة تربيعية للأخطاء الصغيرة وخطية للكبيرة ⇒ القيم الشاذة تُعاقَب أقل.",
       "المعاملات والمقياس σ.", "خطية؛ الشواذ قليلة نسبيًا.", "القياس يسهّل التحسين.", "One-hot.", "لا يدعم NaN.",
       "L-BFGS، تكراري.", ("متين أمام شواذ y", "تفسير كالخطي"), ("ليس متينًا أمام نقاط الرافعة في X بالقدر نفسه",),
       ("شواذ كثيرة جدًا تتجاوز نقطة الانهيار",), ("مقارنة البواقي مع OLS", "outliers_ mask"),
       "كالانحدار الخطي.", ("Huber (1964), doi:10.1214/aoms/1177703732",)),
    _A("logistic", "Logistic Regression", "logistic_regression", "sklearn.linear_model.LogisticRegression",
       ("classification",), True, True, True, "required", False, False, "high", True, False, False,
       "تصنيف ثنائي/متعدد مع احتمالات.", "نموذج خطي لـlog-odds ثم Sigmoid يحوله إلى احتمال؛ الحد خطي.",
       "المعاملات (log-odds لكل وحدة).", "خطية log-odds في الخصائص؛ استقلال الملاحظات.",
       "القياس مهم للتنظيم وللتقارب.", "One-hot.", "لا يدعم NaN.",
       "lbfgs: O(np) لكل تكرار.",
       ("احتمالات معقولة المعايرة غالبًا", "قابل للتفسير (Odds ratios)", "سريع"),
       ("حدود خطية فقط دون خصائص إضافية",), ("فصل تام ⇒ معاملات تتباعد دون تنظيم", "عدم تقارب (ConvergenceWarning)"),
       ("Calibration curve", "معاملات مع CI (statsmodels)", "Learning curve"),
       "exp(β_j) = نسبة الأرجحية (Odds ratio) لزيادة x_j وحدة.",
       ("Hastie et al. (2009), ESL, sec. 4.4",)),
    _A("gaussian_nb", "Gaussian Naive Bayes", "naive_bayes", "sklearn.naive_bayes.GaussianNB", ("classification",), True,
       False, True, "not needed", False, False, "medium", False, True, False,
       "تصنيف سريع جدًا بافتراض الاستقلال الشرطي.", "كل خاصية تُنمذج بتوزيع طبيعي داخل كل فئة ثم نضرب الإمكانات.",
       "متوسط وتباين كل خاصية لكل فئة، والأولويات.", "استقلال شرطي للخصائص بمعلومية الفئة؛ طبيعية داخل الفئة.",
       "لا يحتاج قياسًا.", "استخدم CategoricalNB للفئات.", "لا يدعم NaN.", "O(np) — تمريرة واحدة.",
       ("سريع جدًا", "يعمل مع بيانات قليلة", "partial_fit"), ("احتمالات مفرطة الثقة", "حدود تربيعية بسيطة فقط"),
       ("خصائص مكررة تُحتسب مرتين",), ("Calibration curve",), "theta_ وvar_ لكل فئة.",
       ("Hastie et al. (2009), ESL, sec. 6.6.3",)),
    _A("multinomial_nb", "Multinomial / Complement NB", "naive_bayes", "sklearn.naive_bayes.MultinomialNB",
       ("classification",), True, True, True, "not needed", False, False, "high", False, True, False,
       "تصنيف النصوص بعدّ الكلمات.", "كل فئة «تولّد» الكلمات بتوزيع متعدد الحدود؛ التنبؤ خطي في log-counts.",
       "احتمال كل كلمة لكل فئة.", "استقلال الكلمات بمعلومية الفئة.", "عدّ أو TF-IDF غير سالب.", "—", "لا يدعم NaN.",
       "O(nnz).", ("خط أساس نصي ممتاز", "سريع", "partial_fit"), ("احتمالات غير معايرة",),
       ("كلمة لم تُرَ ⇒ احتمال صفري دون alpha",), ("أكثر الكلمات تمييزًا لكل فئة",), "feature_log_prob_.",
       ("Rennie et al. (2003), ICML — Complement NB",)),
    _A("lda", "Linear Discriminant Analysis", "lda_qda", "sklearn.discriminant_analysis.LinearDiscriminantAnalysis",
       ("classification", "dimred"), True, True, True, "not needed", False, False, "high", True, False, False,
       "تصنيف بنمذجة توزيع كل فئة بتغاير مشترك.", "غاوسيات بنفس الشكل ومراكز مختلفة ⇒ حد خطي؛ وأيضًا إسقاط يفصل الفئات.",
       "متوسطات الفئات والتغاير المشترك.", "طبيعية متعددة داخل الفئة وتغاير متساوٍ.", "—", "One-hot.", "لا يدعم NaN.",
       "O(np²).", ("مستقر مع بيانات قليلة", "تقليل أبعاد موجَّه"), ("افتراض التغاير المشترك",),
       ("p قريب من n ⇒ استخدم shrinkage",), ("مقارنة مع QDA",), "اتجاهات التمييز scalings_.",
       ("Fisher (1936), doi:10.1111/j.1469-1809.1936.tb02137.x",)),
    _A("qda", "Quadratic Discriminant Analysis", "lda_qda", "sklearn.discriminant_analysis.QuadraticDiscriminantAnalysis",
       ("classification",), True, False, True, "not needed", False, False, "medium", True, False, False,
       "تصنيف بحدود تربيعية.", "كل فئة لها غاوسية بشكلها الخاص ⇒ حدود منحنية.", "متوسط وتغاير لكل فئة.",
       "طبيعية داخل الفئة.", "—", "One-hot.", "لا يدعم NaN.", "O(k·np²).", ("حدود مرنة بمعاملات قليلة",),
       ("معاملات كثيرة لكل فئة (p²)",), ("تغاير شبه منفرد ⇒ reg_param",), ("مقارنة مع LDA",), "تغاير كل فئة.",
       ("Hastie et al. (2009), ESL, sec. 4.3",)),
    _A("knn", "k-Nearest Neighbors", "knn", "sklearn.neighbors.KNeighborsClassifier", ("classification", "regression"),
       True, False, False, "required", False, False, "medium", False, False, False,
       "التنبؤ من أقرب الأمثلة المخزنة.", "«قل لي من جيرانك أقل لك من أنت»: تصويت/متوسط أقرب k نقاط.",
       "لا شيء — يخزن التدريب (Lazy learning).", "النقاط القريبة متشابهة الهدف؛ مسافة ذات معنى.",
       "القياس إلزامي.", "One-hot أو مسافة مخصصة.", "لا يدعم NaN.", "تدريب O(1)، تنبؤ O(np) (brute).",
       ("بسيط وغير معلمي", "حدود مرنة جدًا"), ("بطيء في التنبؤ", "لعنة الأبعاد", "حساس للقياس والخصائص عديمة الفائدة"),
       ("خصائص بمقاييس مختلفة تسيطر", "أبعاد عالية ⇒ كل النقاط متباعدة بالتساوي"), ("Validation curve على k",),
       "الجيران أنفسهم تفسير: «هذه الحالات المشابهة».", ("Cover & Hart (1967), doi:10.1109/TIT.1967.1053964",)),
    _A("svm", "Support Vector Machine", "svm", "sklearn.svm.SVC", ("classification", "regression"), True, False, False,
       "required", False, False, "low", False, False, False,
       "تصنيف بأكبر هامش، مع نوى للحدود غير الخطية.", "ارسم أعرض «طريق» يفصل الفئتين؛ الحد يتحدد بالنقاط على الحافة فقط.",
       "المتجهات الداعمة ومعاملاتها الثنائية.", "—", "القياس إلزامي.", "One-hot.", "لا يدعم NaN.",
       "بين O(n²p) وO(n³)؛ الذاكرة لمصفوفة النواة.",
       ("قوي في الأبعاد العالية", "مرن بالنوى", "حل عالمي (مسألة محدبة)"),
       ("لا يتوسع لـn كبير جدًا", "لا احتمالات أصلية", "حساس لـC وgamma"),
       ("gamma كبير ⇒ حفظ", "نسيان القياس"), ("Grid على (C, gamma) لوغاريتمية", "عدد المتجهات الداعمة"),
       "للنواة الخطية: coef_؛ لغيرها صعب التفسير.", ("Cortes & Vapnik (1995), doi:10.1007/BF00994018",)),
    _A("decision_tree", "Decision Tree (CART)", "decision_trees", "sklearn.tree.DecisionTreeClassifier",
       ("classification", "regression"), True, False, False, "not needed", False, True, "high", False, False, False,
       "قواعد if-then متتالية للتصنيف أو الانحدار.", "اسأل أفضل سؤال نعم/لا يقلل الخلط، ثم كرر داخل كل فرع.",
       "بنية الشجرة: خاصية وعتبة كل عقدة وقيمة كل ورقة.", "لا افتراضات توزيعية.",
       "لا يحتاج قياسًا.", "Ordinal/one-hot (لا دعم فئوي أصلي في sklearn).",
       "يدعم NaN في splitter='best' (منذ 1.3).", "تدريب O(n log n · p) لكل مستوى تقريبًا.",
       ("قابل للتفسير", "يلتقط التفاعلات واللاخطية", "لا يحتاج قياسًا"),
       ("تباين عالٍ جدًا", "حدود متدرجة محاذية للمحاور"), ("عمق كامل ⇒ حفظ كامل", "تغير صغير بالبيانات ⇒ شجرة مختلفة"),
       ("Validation curve على max_depth", "مسار التقليم ccp_alpha"), "المسار من الجذر إلى الورقة هو التفسير.",
       ("Breiman et al. (1984), CART; Quinlan (1986), doi:10.1007/BF00116251",)),
    _A("random_forest", "Random Forest", "random_forest", "sklearn.ensemble.RandomForestClassifier",
       ("classification", "regression"), True, False, False, "not needed", False, True, "medium", False, False, True,
       "خفض تباين الأشجار بتجميع أشجار غير مترابطة.",
       "مئات الأشجار، كل منها يرى عينة Bootstrap وخصائص عشوائية عند كل تقسيم، ثم تصويت.",
       "مجموعة الأشجار.", "لا افتراضات توزيعية.", "لا يحتاج قياسًا.", "Ordinal/one-hot.",
       "يدعم NaN منذ 1.4 (تصنيف) و1.9 (absolute_error للانحدار).", "O(B · n log n · √p).",
       ("أداء قوي بلا ضبط كثير", "OOB مجاني", "متين"), ("أقل قابلية للتفسير", "نماذج كبيرة", "لا يستقرئ"),
       ("Impurity importance منحاز للخصائص عالية الكاردينالية",), ("OOB score", "Permutation importance"),
       "Permutation importance وPDP.", ("Breiman (2001), doi:10.1023/A:1010933404324",)),
    _A("extra_trees", "Extra Trees", "random_forest", "sklearn.ensemble.ExtraTreesClassifier",
       ("classification", "regression"), True, False, False, "not needed", False, True, "medium", False, False, True,
       "تجميع أشجار بعتبات عشوائية تمامًا.", "مثل RF لكن العتبة نفسها عشوائية ⇒ تباين أقل وسرعة أكبر.",
       "مجموعة الأشجار.", "—", "لا يحتاج قياسًا.", "Ordinal/one-hot.", "يدعم NaN في الإصدارات الحديثة.",
       "أسرع من RF.", ("سريع", "تباين منخفض"), ("تحيز أعلى قليلًا",), ("بيانات قليلة جدًا",), ("OOB (مع bootstrap=True)",),
       "كـRF.", ("Geurts, Ernst & Wehenkel (2006), doi:10.1007/s10994-006-6226-1",)),
    _A("adaboost", "AdaBoost", "boosting", "sklearn.ensemble.AdaBoostClassifier", ("classification", "regression"), True,
       False, False, "not needed", False, False, "low", False, False, True,
       "تعزيز متعلمين ضعفاء بإعادة الوزن.", "كل متعلم جديد يركز على الأمثلة التي أخطأ فيها السابقون (أوزان أعلى).",
       "المتعلمون وأوزانهم.", "—", "لا يحتاج قياسًا (مع الأشجار).", "Ordinal/one-hot.", "حسب المتعلم الأساسي.",
       "O(M · تكلفة المتعلم).", ("بسيط ونظريًا أنيق",), ("حساس للضجيج والشواذ في التسميات",),
       ("تسميات خاطئة تحصل على أوزان ضخمة",), ("staged_score",), "—",
       ("Freund & Schapire (1997), doi:10.1006/jcss.1997.1504",)),
    _A("gradient_boosting", "Gradient Boosting", "boosting", "sklearn.ensemble.GradientBoostingClassifier",
       ("classification", "regression"), True, False, False, "not needed", False, False, "low", False, False, True,
       "بناء نموذج جمعي بتصحيح البواقي تدريجيًا.", "كل شجرة صغيرة تتعلم «ما تبقى من الخطأ» (التدرج السالب للخسارة).",
       "الأشجار ومعدل التعلّم.", "—", "لا يحتاج قياسًا.", "Ordinal/one-hot.", "لا يدعم NaN (استخدم HGB).",
       "O(M · n log n · p) — تسلسلي.", ("دقة عالية", "أي خسارة قابلة للاشتقاق"), ("بطيء على n كبير", "تسلسلي"),
       ("مراحل كثيرة مع learning_rate كبير ⇒ Overfitting",), ("staged_predict + منحنى التحقق",), "Permutation/SHAP.",
       ("Friedman (2001), doi:10.1214/aos/1013203451",)),
    _A("hist_gb", "HistGradientBoosting", "hist_gradient_boosting", "sklearn.ensemble.HistGradientBoostingClassifier",
       ("classification", "regression"), True, False, False, "not needed", True, True, "low", False, False, True,
       "تعزيز سريع للبيانات الجدولية الكبيرة.", "قطّع كل خاصية إلى ≤255 صندوقًا ثم ابحث عن التقسيمات بين الصناديق.",
       "الأشجار وحدود الصناديق.", "—", "لا يحتاج قياسًا.", "أصلي (categorical_features، أعمدة category).",
       "أصلي: يتعلم اتجاه NaN في كل تقسيم.", "O(M · n · p) تقريبًا — سريع جدًا.",
       ("سريع جدًا", "فئات وقيم مفقودة أصلية", "توقف مبكر"), ("أقل قابلية للتفسير",),
       ("early_stopping='auto' قد يتفعل دون انتباه (n>10000)",), ("validation_score_",), "Permutation/PDP/SHAP.",
       ("Ke et al. (2017), NeurIPS — histogram GBDT",)),
    _A("xgboost", "XGBoost", "xgboost", "xgboost.XGBClassifier", ("classification", "regression"), True, False, False,
       "not needed", True, True, "low", False, False, True,
       "تعزيز منظَّم عالي الأداء.", "تقريب تربيعي (تدرج + هيسيان) للخسارة مع عقوبة على عدد الأوراق وأوزانها.",
       "الأشجار وأوزان الأوراق.", "—", "لا يحتاج قياسًا.", "أصلي مع enable_categorical=True.",
       "أصلي (اتجاه افتراضي متعلَّم).", "hist: O(M · n · p).",
       ("دقة ممتازة", "تنظيم غني", "GPU"), ("معاملات كثيرة",), ("gamma/min_child_weight غير مضبوطة",),
       ("evals_result + early stopping",), "SHAP (TreeSHAP أصلي pred_contribs).",
       ("Chen & Guestrin (2016), doi:10.1145/2939672.2939785",)),
    _A("lightgbm", "LightGBM", "lightgbm", "lightgbm.LGBMClassifier", ("classification", "regression"), True, False,
       False, "not needed", True, True, "low", False, False, True,
       "تعزيز سريع جدًا للبيانات الكبيرة.", "نمو Leaf-wise: وسّع دائمًا الورقة ذات أكبر ربح، مع مدرجات.",
       "الأشجار.", "—", "لا يحتاج قياسًا.", "أصلي (category dtype).", "أصلي.", "سريع جدًا، ذاكرة منخفضة.",
       ("الأسرع غالبًا", "فئات أصلية"), ("Leaf-wise يفرط مع بيانات صغيرة",), ("num_leaves كبير مع n صغير",),
       ("early stopping callback",), "SHAP (pred_contrib).",
       ("Ke et al. (2017), NeurIPS 30",)),
    _A("catboost", "CatBoost", "catboost", "catboost.CatBoostClassifier", ("classification", "regression"), True, False,
       False, "not needed", True, True, "low", False, False, True,
       "تعزيز قوي مع متغيرات فئوية كثيرة.", "Target statistics مرتّبة زمنيًا ضمنيًا + Ordered boosting لتجنب تسرب الهدف.",
       "الأشجار المتناظرة.", "—", "لا يحتاج قياسًا.", "أصلي (cat_features) — الأقوى في هذا.",
       "أصلي للعددية (Min افتراضيًا).", "أبطأ في التدريب، سريع جدًا في التنبؤ.",
       ("إعدادات افتراضية قوية", "فئات عالية الكاردينالية"), ("تدريب أبطأ",), ("One-hot مسبق يُضيّع ميزته",),
       ("eval_set + use_best_model",), "SHAP أصلي (get_feature_importance type='ShapValues').",
       ("Prokhorenkova et al. (2018), NeurIPS 31, arXiv:1706.09516",)),
    _A("mlp", "Multilayer Perceptron", "dl_bridge", "sklearn.neural_network.MLPClassifier", ("classification", "regression"),
       True, False, True, "required", False, False, "low", False, True, False,
       "تقريب دوال مرنة بطبقات من الوحدات غير الخطية.", "تركيب دوال بسيطة (خطي + تنشيط) طبقة فوق طبقة.",
       "الأوزان والانحيازات.", "—", "القياس إلزامي.", "One-hot.", "لا يدعم NaN.", "O(epochs · n · weights).",
       ("مرن جدًا", "partial_fit"), ("حساس للمعاملات والبداية", "صعب التفسير"), ("عدم تقارب", "نهايات محلية"),
       ("loss_curve_",), "—", ("Rumelhart, Hinton & Williams (1986), doi:10.1038/323533a0",)),
    _A("kmeans", "K-Means", "kmeans", "sklearn.cluster.KMeans", ("clustering",), False, True, True, "required", False,
       False, "high", False, True, False,
       "تقسيم البيانات إلى k عناقيد كروية.", "كرر: عيّن كل نقطة لأقرب مركز، ثم انقل المركز إلى متوسط نقاطه.",
       "المراكز cluster_centers_.", "عناقيد كروية متقاربة الحجم.", "القياس إلزامي.", "—", "لا يدعم NaN.",
       "O(n·k·p) لكل تكرار.", ("سريع وبسيط", "MiniBatchKMeans للبيانات الكبيرة"),
       ("يجب تحديد k", "يفشل مع أشكال غير كروية"), ("بدايات سيئة", "مقاييس مختلفة"), ("Silhouette", "Elbow"),
       "المراكز تلخّص كل عنقود.", ("Lloyd (1982), doi:10.1109/TIT.1982.1056489",)),
    _A("hierarchical", "Agglomerative Clustering", "hierarchical", "sklearn.cluster.AgglomerativeClustering",
       ("clustering",), False, False, False, "required", False, False, "high", False, False, False,
       "بناء شجرة دمج للعناقيد.", "ابدأ بكل نقطة عنقودًا ثم ادمج الأقرب مرارًا.", "شجرة الدمج.", "—", "القياس إلزامي.",
       "—", "لا يدعم NaN.", "O(n²) ذاكرة.", ("Dendrogram مفسّر", "لا حاجة لـk مسبقًا"), ("لا يتوسع",),
       ("single linkage ⇒ تسلسل (chaining)",), ("Dendrogram",), "مستويات الشجرة.", ("Ward (1963), doi:10.1080/01621459.1963.10500845",)),
    _A("dbscan", "DBSCAN", "dbscan", "sklearn.cluster.DBSCAN", ("clustering", "anomaly"), False, False, False, "required",
       False, False, "high", False, False, False,
       "عناقيد بأي شكل حسب الكثافة مع تحديد الضجيج.", "النقاط في المناطق الكثيفة تتصل ببعضها؛ المعزولة ضجيج.",
       "تسميات ونقاط مركزية.", "كثافة متقاربة بين العناقيد.", "القياس إلزامي.", "—", "لا يدعم NaN.",
       "O(n log n) مع فهرس.", ("أشكال عشوائية", "يحدد الضجيج"), ("eps واحد لكل الكثافات",),
       ("كثافات مختلفة ⇒ فشل",), ("k-distance plot",), "core_sample_indices_.",
       ("Ester et al. (1996), KDD-96",)),
    _A("hdbscan", "HDBSCAN", "dbscan", "sklearn.cluster.HDBSCAN", ("clustering", "anomaly"), False, False, False,
       "required", False, False, "high", False, False, False,
       "DBSCAN هرمي لكثافات متفاوتة.", "يبني شجرة كثافة ويختار العناقيد الأكثر ثباتًا.", "تسميات واحتمالات.",
       "—", "القياس إلزامي.", "—", "يدعم NaN جزئيًا حسب المقياس.", "O(n log n) تقريبًا.",
       ("لا يحتاج eps", "كثافات متفاوتة"), ("أبطأ من DBSCAN",), ("min_cluster_size غير مناسب",), ("probabilities_",),
       "—", ("Campello, Moulavi & Sander (2013), doi:10.1007/978-3-642-37456-2_14",)),
    _A("gmm", "Gaussian Mixture", "gmm", "sklearn.mixture.GaussianMixture", ("clustering", "anomaly"), False, False, True,
       "recommended", False, False, "medium", True, False, False,
       "تجميع احتمالي ناعم.", "البيانات خليط من عدة غاوسيات؛ EM يقدّر من ولّد كل نقطة.",
       "الأوزان والمتوسطات والتغايرات.", "مكونات غاوسية.", "القياس مستحسن.", "—", "لا يدعم NaN.", "O(n·k·p²) لكل تكرار.",
       ("عضوية ناعمة", "BIC لاختيار k"), ("نهايات محلية",), ("تغاير منفرد",), ("BIC/AIC", "converged_"), "المكونات.",
       ("Dempster, Laird & Rubin (1977), doi:10.1111/j.2517-6161.1977.tb01600.x",)),
    _A("pca", "PCA", "pca", "sklearn.decomposition.PCA", ("dimred",), False, True, True, "required", False, False,
       "medium", False, True, False,
       "ضغط الخصائص في اتجاهات تباين قصوى.", "دوّر المحاور لتتجه نحو أكبر انتشار للبيانات.",
       "المكونات (Loadings) والتباين المفسر.", "العلاقات خطية؛ التباين = معلومات.", "القياس إلزامي عادة.", "—",
       "لا يدعم NaN.", "SVD: O(min(n p², n² p)).", ("سريع ودقيق", "إزالة ترابط"), ("خطي فقط", "المكونات صعبة التسمية"),
       ("نسيان القياس ⇒ المتغير الأكبر مقياسًا يسيطر",), ("Scree plot",), "Loadings.",
       ("Pearson (1901), doi:10.1080/14786440109462720",)),
    _A("tsne", "t-SNE", "manifold", "sklearn.manifold.TSNE", ("dimred",), False, False, False, "recommended", False,
       False, "low", False, False, False,
       "تصوير البنية المحلية في بعدين.", "حافظ على من هو جار من في الأبعاد العالية.", "الإحداثيات فقط (لا transform).",
       "—", "القياس مستحسن؛ PCA أولًا للأبعاد العالية.", "—", "لا يدعم NaN.", "O(n log n) مع Barnes-Hut.",
       ("خرائط بصرية ممتازة",), ("لا يحفظ المسافات العالمية", "غير قابل للتطبيق على بيانات جديدة"),
       ("قراءة أحجام العناقيد والمسافات بينها",), ("عدة قيم perplexity",), "بصري فقط.",
       ("van der Maaten & Hinton (2008), JMLR 9",)),
    _A("isolation_forest", "Isolation Forest", "anomaly_detection", "sklearn.ensemble.IsolationForest", ("anomaly",),
       False, False, False, "not needed", False, True, "medium", False, False, True,
       "كشف الشذوذ بالعزل.", "النقطة الشاذة تُعزَل بتقسيمات عشوائية قليلة.", "أشجار العزل.", "الشذوذ قليل ومختلف.",
       "لا يحتاج قياسًا.", "Ordinal.", "يدعم NaN في الإصدارات الحديثة.", "O(t · ψ log ψ).",
       ("سريع", "أبعاد عالية"), ("contamination يحدد العتبة فقط",), ("شذوذ جماعي كثيف",), ("score_samples",), "درجة الشذوذ.",
       ("Liu, Ting & Zhou (2008), doi:10.1109/ICDM.2008.17",)),
    _A("lof", "Local Outlier Factor", "anomaly_detection", "sklearn.neighbors.LocalOutlierFactor", ("anomaly",), False,
       False, False, "required", False, False, "medium", False, False, False,
       "شذوذ نسبي لكثافة الجوار.", "النقطة شاذة إن كانت كثافتها أقل بكثير من كثافة جيرانها.", "—", "—", "القياس إلزامي.",
       "—", "لا يدعم NaN.", "O(n²) brute.", ("شذوذ محلي",), ("novelty=True مطلوب للبيانات الجديدة",), ("k صغير جدًا",),
       ("negative_outlier_factor_",), "نسبة الكثافة.", ("Breunig et al. (2000), doi:10.1145/335191.335388",)),
    _A("ocsvm", "One-Class SVM", "anomaly_detection", "sklearn.svm.OneClassSVM", ("anomaly",), False, False, False,
       "required", False, False, "low", False, False, False,
       "حدود حول البيانات الطبيعية.", "افصل البيانات عن الأصل في فضاء النواة.", "المتجهات الداعمة.", "—",
       "القياس إلزامي.", "—", "لا يدعم NaN.", "O(n²)–O(n³).", ("حدود مرنة",), ("حساس لـnu وgamma",), ("بيانات تدريب ملوثة",),
       ("decision_function",), "—", ("Schölkopf et al. (2001), doi:10.1162/089976601750264965",)),
    # ------------------------------------------------ imbalanced-learn ensembles (module imb_ensembles)
    _A("balanced_rf", "Balanced Random Forest", "imb_ensembles", "imblearn.ensemble.BalancedRandomForestClassifier",
       ("classification",), True, False, False, "not needed", False, True, "medium", False, False, True,
       "غابة عشوائية لبيانات غير متوازنة دون التضحية بمعظم أشجارها لصالح الأغلبية.",
       "كل شجرة تُدرَّب على عينة متوازنة: Bootstrap من الأقلية وسحب بالحجم نفسه من الأغلبية، ثم تصويت.",
       "مجموعة الأشجار (estimators_) والـSamplers المرافقة (samplers_).",
       "لا افتراضات توزيعية؛ يفترض أن الأغلبية المحذوفة في كل شجرة تُغطّى عبر الأشجار الأخرى.",
       "لا قياس؛ ترميز الفئات.", "Ordinal أو one-hot.", "يقبل NaN (تم التحقق على 0.14.2 مع أشجار scikit-learn الحديثة).",
       "O(B · m log m · √p) حيث m ≈ 2 × حجم الأقلية ⇒ أسرع من RF على كامل البيانات.",
       ("Recall مرتفع للأقلية دون ضبط", "أسرع من RF لأن كل شجرة ترى عينة صغيرة", "واجهة RF المعروفة"),
       ("احتمالات غير معايرة (متوسطها أعلى بكثير من الانتشار)", "يهمل جزءًا من الأغلبية في كل شجرة",
        "قد يخفض Precision وPR-AUC مقارنة بـRF مضبوط العتبة"),
       ("أقلية صغيرة جدًا ⇒ كل شجرة ترى عينة ضئيلة وتباين عالٍ", "استخدام الاحتمالات كاحتمالات حقيقية"),
       ("PR-AUC مقابل RF + عتبة مضبوطة", "Reliability diagram", "mean p مقابل الانتشار"),
       "Permutation importance على بيانات تحقق بالانتشار الحقيقي.",
       ("Chen, Liaw & Breiman (2004), UC Berkeley TR 666",)),
    _A("balanced_bagging", "Balanced Bagging", "imb_ensembles", "imblearn.ensemble.BalancedBaggingClassifier",
       ("classification",), True, False, False, "not needed", False, True, "medium", False, False, True,
       "Bagging حيث تُعاد موازنة كل حقيبة قبل تدريب المُقدِّر الأساسي.",
       "كل حقيبة = عينة متوازنة (RandomUnderSampler افتراضيًا أو أي Sampler آخر) ⇒ مقدرات متنوعة ومتوازنة.",
       "المقدرات الأساسية (estimators_) وSamplers كل حقيبة.", "كالـBagging: يفيد أكثر مع المقدرات غير المستقرة.",
       "حسب المقدر الأساسي (الافتراضي شجرة قرار).", "حسب المقدر الأساسي.",
       "مع الشجرة الافتراضية يقبل NaN (تم التحقق على 0.14.2).", "B × تكلفة المقدر على عينة الحقيبة.",
       ("مرن: أي Sampler وأي مقدر", "يدعم OOB", "تباين أقل من إعادة عيّنة واحدة"),
       ("احتمالات غير معايرة", "10 حقائب افتراضيًا قد لا تكفي"),
       ("Sampler يولّد نقاطًا (SMOTE) مع ضجيج ⇒ حقائب مضللة",), ("OOB score", "PR-AUC عبر CV"),
       "كما في Bagging: أهمية بالتبديل على بيانات التحقق.",
       ("Breiman (1996), doi:10.1007/BF00058655", "Lemaître et al. (2017), JMLR 18(17)")),
    _A("easy_ensemble", "EasyEnsemble", "imb_ensembles", "imblearn.ensemble.EasyEnsembleClassifier",
       ("classification",), True, False, False, "not needed", False, False, "low", False, False, True,
       "استكشاف الأغلبية كلها عبر عدة عيّنات متوازنة بدل رميها.",
       "n_estimators عيّنة متوازنة من الأغلبية مع كل الأقلية؛ على كل منها AdaBoost كامل؛ ثم دمج.",
       "مجموعة نماذج AdaBoost.", "كالـBoosting: المقدرات الضعيفة أفضل من الصدفة على كل عيّنة.", "لا قياس.",
       "Ordinal أو one-hot.", "لا يقبل NaN (AdaBoost؛ تم التحقق على 0.14.2).",
       "n_estimators × مراحل AdaBoost × تكلفة الشجرة ⇒ الأبطأ بين التجميعات المتوازنة.",
       ("يستخدم معلومات الأغلبية كلها عبر العيّنات", "Recall مرتفع"),
       ("بطيء", "احتمالات غير معايرة", "Precision منخفض غالبًا عند العتبة 0.5"),
       ("تداخل كبير ⇒ AdaBoost يطارد الضجيج",), ("PR-AUC", "زمن التدريب"), "ضعيف: مجموعة من مجموعات.",
       ("Liu, Wu & Zhou (2009), doi:10.1109/TSMCB.2008.2007853",)),
    _A("rusboost", "RUSBoost", "imb_ensembles", "imblearn.ensemble.RUSBoostClassifier", ("classification",), True,
       False, False, "not needed", False, False, "low", False, False, True,
       "Boosting يعيد موازنة البيانات قبل كل مرحلة.",
       "قبل كل مرحلة AdaBoost: RandomUnderSampler على البيانات الموزونة، ثم تحديث الأوزان كالمعتاد.",
       "المقدرات الضعيفة وأوزانها (estimator_weights_).", "مقدر ضعيف أفضل من الصدفة في كل مرحلة.",
       "لا قياس.", "Ordinal أو one-hot.", "لا يقبل NaN (تم التحقق على 0.14.2).", "سريع: كل مرحلة على عينة صغيرة.",
       ("سريع جدًا", "بسيط"),
       ("هش: الجذوع الافتراضية قد ترفع خطأ «worse than random»", "حساس لـlearning_rate", "احتمالات غير معايرة"),
       ("خطأ أثناء fit على بيانات متداخلة (depth 1 أو 2)", "أداء متقلب بين البذور"),
       ("staged_predict_proba", "الاستقرار عبر random_state"), "ضعيف.",
       ("Seiffert et al. (2010), doi:10.1109/TSMCA.2009.2029559",)),
)

ALGO_BY_ID: dict[str, Algorithm] = {a.id: a for a in ALGORITHMS}


def get_algorithm(algo_id: str) -> Algorithm:
    return ALGO_BY_ID[algo_id]
