"""Arabic/English glossary (section 76). Each entry: (english, arabic, definition, module_id)."""

from __future__ import annotations

GLOSSARY: tuple[tuple[str, str, str, str], ...] = (
    ("Estimator", "المقدِّر", "كائن يتعلم من البيانات عبر fit(). في الإحصاء: دالة من العينة تقدّر معلمة مجتمع.", "ml_vocabulary"),
    ("Algorithm", "الخوارزمية", "إجراء تعلّم عام (مثل CART أو Gradient descent) يحوّل بيانات إلى نموذج.", "ml_vocabulary"),
    ("Model", "النموذج", "ناتج تطبيق الخوارزمية على بيانات محددة: دالة بمعاملات متعلَّمة.", "ml_vocabulary"),
    ("Parameter", "المعامل (المتعلَّم)", "قيمة يتعلمها النموذج من البيانات (مثل coef_ أو عتبات الشجرة).", "ml_vocabulary"),
    ("Hyperparameter", "المعامل الفائق", "قيمة تُختار قبل التدريب وتتحكم في التعلّم (مثل max_depth أو C).", "ml_vocabulary"),
    ("Feature", "الخاصية / المتغير المفسِّر", "عمود من X يُستخدم للتنبؤ.", "feature_matrix"),
    ("Target", "الهدف", "المتغير y الذي نريد التنبؤ به.", "feature_matrix"),
    ("Feature matrix", "مصفوفة الخصائص", "المصفوفة X بحجم n × p: صف لكل ملاحظة وعمود لكل خاصية.", "feature_matrix"),
    ("Loss", "الخسارة", "دالة تقيس خطأ تنبؤ واحد ℓ(y, ŷ).", "loss_functions"),
    ("Objective", "دالة الهدف", "ما يُحسَّن فعليًا أثناء التدريب: متوسط الخسارة + عقوبة التنظيم.", "loss_functions"),
    ("Metric", "المقياس", "ما نبلغ عنه لتقييم النموذج؛ قد يختلف عن الخسارة (مثل AUC).", "loss_functions"),
    ("Empirical risk", "المخاطرة التجريبية", "متوسط الخسارة على عينة التدريب.", "statistical_learning"),
    ("Expected risk", "المخاطرة المتوقعة", "متوسط الخسارة على توزيع المجتمع كاملًا (غير معروف).", "statistical_learning"),
    ("Generalization", "التعميم", "أداء النموذج على بيانات جديدة من نفس التوزيع.", "statistical_learning"),
    ("Overfitting", "فرط الملاءمة", "حفظ ضجيج التدريب: أداء تدريب ممتاز وأداء تحقق ضعيف.", "bias_variance"),
    ("Underfitting", "نقص الملاءمة", "نموذج أبسط من البنية الحقيقية: أداء ضعيف في التدريب والتحقق.", "bias_variance"),
    ("Bias", "التحيّز", "الفرق بين متوسط تنبؤات النموذج (عبر عينات) والقيمة الحقيقية.", "bias_variance"),
    ("Variance", "التباين", "تقلّب تنبؤات النموذج عند تغيير عينة التدريب.", "bias_variance"),
    ("Regularization", "التنظيم", "إضافة قيد أو عقوبة على التعقيد لتحسين التعميم.", "regularization"),
    ("Capacity", "السعة", "مدى مرونة فضاء الدوال الذي يستطيع النموذج تمثيله.", "learning_theory"),
    ("VC dimension", "بُعد VC", "أكبر عدد نقاط يستطيع فضاء الفرضيات تمزيقها (Shatter) بكل التسميات الممكنة.", "learning_theory"),
    ("Gradient", "التدرّج", "متجه المشتقات الجزئية؛ يشير إلى اتجاه أسرع صعود.", "calculus"),
    ("Learning rate", "معدل التعلّم", "حجم الخطوة في الانحدار التدرجي، أو الانكماش في التعزيز.", "gradient_descent"),
    ("Convexity", "التحدّب", "دالة أي نهاية صغرى محلية لها هي عالمية.", "optimization_intro"),
    ("Early stopping", "التوقف المبكر", "إيقاف التدريب حين يتوقف تحسن أداء التحقق؛ شكل من التنظيم.", "advanced_optimizers"),
    ("Margin", "الهامش", "المسافة بين حد القرار وأقرب نقاط التدريب (SVM)؛ أو y·f(x) في الخسائر.", "svm"),
    ("Support vectors", "المتجهات الداعمة", "نقاط التدريب التي تحدد الحد في SVM (على الهامش أو داخله).", "svm"),
    ("Kernel", "النواة", "دالة تشابه K(x, x') تعادل جداءً داخليًا في فضاء خصائص ضمني.", "svm"),
    ("Kernel trick", "خدعة النواة", "حساب الجداء الداخلي في فضاء عالي الأبعاد دون حساب الإسقاط صراحة.", "svm"),
    ("Impurity", "الشوائب (عدم النقاء)", "مقياس خلط الفئات في عقدة: Gini أو الإنتروبيا.", "decision_trees"),
    ("Information gain", "كسب المعلومات", "انخفاض الشوائب بعد التقسيم.", "decision_trees"),
    ("Pruning", "التقليم", "إزالة فروع الشجرة لتقليل Overfitting (مثل ccp_alpha).", "decision_trees"),
    ("Ensemble", "التجميع", "دمج عدة نماذج (Bagging, Boosting, Stacking) في تنبؤ واحد.", "ensemble_learning"),
    ("Bagging", "التجميع بالإقلاع", "تدريب نماذج على عينات Bootstrap ثم المتوسط/التصويت لخفض التباين.", "ensemble_learning"),
    ("Boosting", "التعزيز", "بناء نماذج ضعيفة تسلسليًا يصحح كل منها أخطاء ما قبله.", "boosting"),
    ("Out-of-bag (OOB)", "خارج الحقيبة", "الملاحظات التي لم تدخل عينة Bootstrap لشجرة ما؛ تُستخدم للتقييم.", "random_forest"),
    ("Cross-validation", "التحقق المتقاطع", "تقدير الأداء بتدوير أجزاء البيانات بين التدريب والتحقق.", "cross_validation"),
    ("Nested CV", "التحقق المتقاطع المتداخل", "حلقة داخلية للضبط وخارجية لتقييم الإجراء كاملًا.", "cross_validation"),
    ("Data leakage", "تسرّب البيانات", "دخول معلومات لن تتوفر لحظة التنبؤ إلى التدريب أو التقييم.", "leakage"),
    ("Pipeline", "خط المعالجة", "سلسلة خطوات معالجة + نموذج تُدرَّب معًا داخل كل طية.", "pipelines"),
    ("Baseline", "خط الأساس", "نموذج بسيط جدًا للمقارنة (المتوسط، الفئة الأكثر شيوعًا).", "baselines"),
    ("Confusion matrix", "مصفوفة الالتباس", "جدول TP/FP/FN/TN.", "classification_metrics"),
    ("Precision", "الدقة (الإيجابية)", "من بين المتنبأ بها موجبة، كم منها موجب فعلًا؟ TP/(TP+FP).", "classification_metrics"),
    ("Recall", "الاستدعاء (الحساسية)", "من بين الموجبات الفعلية، كم التقطنا؟ TP/(TP+FN).", "classification_metrics"),
    ("ROC-AUC", "المساحة تحت منحنى ROC", "احتمال أن تحصل حالة موجبة عشوائية على درجة أعلى من سالبة عشوائية.", "classification_metrics"),
    ("Average precision", "متوسط الدقة", "ملخص منحنى Precision-Recall؛ أنسب مع الندرة.", "classification_metrics"),
    ("Threshold", "العتبة", "القيمة التي تُحوَّل عندها الاحتمالات إلى قرارات.", "threshold_tuning"),
    ("Calibration", "المعايرة", "تطابق الاحتمالات المتنبأ بها مع التكرارات الفعلية.", "calibration"),
    ("Brier score", "درجة Brier", "متوسط مربع الفرق بين الاحتمال والنتيجة 0/1.", "calibration"),
    ("Prevalence", "الانتشار", "نسبة الفئة الموجبة في المجتمع.", "imbalanced"),
    ("SMOTE", "SMOTE", "توليد أمثلة اصطناعية للفئة النادرة بالاستيفاء بين الجيران.", "imbalanced"),
    ("Conformal prediction", "التنبؤ المطابق", "فترات تنبؤ بتغطية مضمونة تحت قابلية التبادل.", "conformal_prediction"),
    ("Search space", "فضاء البحث", "المجال المسموح لكل معامل فائق أثناء الضبط.", "hpo_foundations"),
    ("Trial", "المحاولة", "تقييم واحد لمجموعة معاملات فائقة.", "bayesian_optimization"),
    ("Surrogate model", "النموذج البديل", "نموذج رخيص يقرّب دالة الهدف في التحسين البايزي.", "bayesian_optimization"),
    ("Pruner", "المُقلِّم (Optuna)", "آلية توقف المحاولات غير الواعدة مبكرًا.", "bayesian_optimization"),
    ("Inertia", "العطالة", "مجموع مربعات المسافات إلى أقرب مركز في K-Means.", "kmeans"),
    ("Silhouette", "معامل الظل", "مقارنة قرب النقطة من عنقودها مقابل أقرب عنقود آخر (−1 إلى 1).", "kmeans"),
    ("Explained variance", "التباين المفسَّر", "نسبة التباين الكلي التي يلتقطها كل مكون رئيسي.", "pca"),
    ("Loadings", "التحميلات", "أوزان الخصائص الأصلية في كل مكون رئيسي.", "pca"),
    ("Novelty", "الجِدّة", "ملاحظة جديدة تختلف عن بيانات تدريب نظيفة (novelty detection).", "anomaly_detection"),
    ("Permutation importance", "أهمية التبديل", "انخفاض الأداء حين تُخلط قيم خاصية عشوائيًا.", "model_inspection"),
    ("Partial dependence", "الاعتماد الجزئي", "متوسط التنبؤ حين تُثبَّت خاصية على قيمة ويُترك الباقي كما هو.", "pdp_ice"),
    ("SHAP value", "قيمة SHAP", "مساهمة الخاصية في تنبؤ محدد وفق قيم Shapley.", "shap"),
    ("Treatment", "المعالجة", "المتغير الذي نريد أثره السببي D.", "causal_foundations"),
    ("Outcome", "النتيجة", "المتغير المتأثر Y.", "causal_foundations"),
    ("Confounder", "متغير مُربِك", "متغير يؤثر في المعالجة والنتيجة معًا.", "causal_foundations"),
    ("Potential outcomes", "النتائج الكامنة", "Y(1) وY(0): النتيجة لو عولجت الوحدة ولو لم تعالَج.", "causal_foundations"),
    ("Counterfactual", "الواقع المضاد", "النتيجة الكامنة غير الملاحَظة.", "causal_foundations"),
    ("ATE", "متوسط الأثر", "E[Y(1) − Y(0)] على كامل المجتمع.", "causal_foundations"),
    ("ATT", "متوسط الأثر على المعالَجين", "E[Y(1) − Y(0) | D = 1].", "causal_foundations"),
    ("CATE", "الأثر الشرطي", "τ(x) = E[Y(1) − Y(0) | X = x].", "hte"),
    ("GATE", "أثر المجموعة", "متوسط الأثر داخل مجموعة معرّفة مسبقًا.", "hte"),
    ("Overlap / Positivity", "التداخل / الإيجابية", "0 < P(D = 1 | X) < 1 لكل x.", "causal_foundations"),
    ("Unconfoundedness", "عدم الإرباك", "(Y(1), Y(0)) ⫫ D | X: لا مربكات غير ملاحَظة.", "causal_foundations"),
    ("Nuisance function", "دالة الإزعاج", "دالة نحتاج تقديرها لكنها ليست هدفنا (مثل E[Y|X] وE[D|X]).", "dml_core"),
    ("Orthogonal score", "الدرجة المتعامدة", "دالة عزم ψ مشتقتها بالنسبة للإزعاج صفر عند القيم الحقيقية.", "neyman_orthogonality"),
    ("Neyman orthogonality", "تعامد Neyman", "عدم حساسية شرط العزم من الرتبة الأولى لأخطاء تقدير الإزعاج.", "neyman_orthogonality"),
    ("Cross-fitting", "المواءمة المتقاطعة", "تقدير الإزعاج على طيات وتقييم الدرجة على الطية المتبقية ثم التدوير.", "cross_fitting"),
    ("Instrument", "المتغير الأداتي", "متغير يؤثر في المعالجة ولا يؤثر في النتيجة إلا عبرها.", "pliv"),
    ("LATE", "الأثر المحلي", "متوسط الأثر على المطيعين (Compliers).", "iivm"),
    ("Propensity score", "درجة الميل", "m(x) = P(D = 1 | X = x).", "irm"),
    ("Doubly robust", "مزدوج المتانة", "مقدِّر متسق إذا صح نموذج النتيجة أو نموذج الميل.", "irm"),
    ("Parallel trends", "الاتجاهات المتوازية", "افتراض DiD: كانت المجموعتان ستتغيران بالمقدار نفسه دون معالجة.", "panel_did"),
    ("Data drift", "انجراف البيانات", "تغير توزيع X بين التدريب والنشر.", "drift"),
    ("Concept drift", "انجراف المفهوم", "تغير العلاقة P(y | X) نفسها.", "drift"),
    ("Model registry", "سجل النماذج", "مخزن مُصدَّر للنماذج مع حالتها (staging/production).", "mlops"),
    ("Demographic parity", "التكافؤ الديموغرافي", "معدل التنبؤ الموجب متساوٍ بين المجموعات.", "fairness"),
    ("Equal opportunity", "تكافؤ الفرص", "معدل الموجب الحقيقي (Recall) متساوٍ بين المجموعات.", "fairness"),
    ("Policy", "السياسة", "في RL: قاعدة اختيار الفعل بناءً على الحالة π(a|s).", "rl_bridge"),
    ("Backpropagation", "الانتشار العكسي", "حساب تدرجات الشبكة بقاعدة السلسلة من المخرج إلى المدخل.", "dl_bridge"),
    ("Epoch", "الحقبة", "مرور كامل واحد على بيانات التدريب.", "dl_bridge"),
    ("TF-IDF", "TF-IDF", "وزن الكلمة = تكرارها في الوثيقة × ندرتها عبر الوثائق.", "text_ml"),
    # Breiman
    ("Two cultures", "الثقافتان", "تمييز Breiman (2001) بين نمذجة البيانات (نموذج عشوائي مفترض) والنمذجة الخوارزمية "
     "(دالة تنبؤ تُحكم بالدقة خارج العينة).", "breiman_two_cultures"),
    ("Algorithmic modeling", "النمذجة الخوارزمية", "معاملة آلية توليد البيانات كمجهولة والبحث عن f(x) تتنبأ جيدًا.",
     "breiman_two_cultures"),
    ("Goodness of fit", "جودة الملاءمة", "اختبار توافق البيانات مع نموذج مفترض؛ قد يكون ضعيف القوة أمام مواصفة ناقصة.",
     "breiman_two_cultures"),
    ("Rashomon effect", "تأثير راشومون", "وجود نماذج كثيرة مختلفة بدقة متقاربة جدًا تروي قصصًا مختلفة عن البيانات.",
     "breiman_three_lessons"),
    ("Rashomon set", "مجموعة راشومون", "كل النماذج في فئة ما التي تقع خسارتها ضمن ε من أفضل نموذج.", "breiman_three_lessons"),
    ("Occam's dilemma", "معضلة أوكام", "التعارض المحتمل بين الدقة التنبؤية وبساطة النموذج وقابليته للتفسير.",
     "breiman_three_lessons"),
    ("Out-of-bag (OOB)", "خارج الحقيبة", "الصفوف التي لم تدخل عينة Bootstrap لشجرة ما (≈ 36.8%)؛ تعطي تقديرًا مجانيًا للخطأ.",
     "breiman_legacy"),
    ("Unstable procedure", "إجراء غير مستقر", "خوارزمية يتغير ناتجها كثيرًا بتغير صغير في بيانات التدريب (مثل الأشجار).",
     "breiman_legacy"),
    # imbalanced classification
    ("Imbalance ratio", "نسبة عدم التوازن", "حجم الفئة الأكبر مقسومًا على حجم الفئة الأصغر (IR).", "imb_nature"),
    ("Absolute rarity", "الندرة المطلقة", "قلة عدد أمثلة الأقلية نفسه، بغض النظر عن نسبتها.", "imb_nature"),
    ("Small disjuncts", "الجزر الصغيرة", "عناقيد صغيرة من الأقلية في مناطق متفرقة من فضاء الخصائص.", "imb_nature"),
    ("MCC", "معامل ارتباط ماثيوز", "ارتباط بين التنبؤ والحقيقة يستخدم خلايا مصفوفة الالتباس الأربع؛ بين −1 و+1.", "imb_metrics"),
    ("G-mean", "المتوسط الهندسي", "√(Recall × Specificity): يعاقب إهمال أي من الفئتين.", "imb_metrics"),
    ("Balanced accuracy", "الدقة المتوازنة", "متوسط Recall لكل فئة.", "imb_metrics"),
    ("PR-AUC", "المساحة تحت منحنى الدقة-الاستدعاء", "ملخص منحنى Precision–Recall؛ خط أساسه الانتشار.", "imb_metrics"),
    ("Cost matrix", "مصفوفة التكلفة", "تكلفة كل خلية من خلايا القرار (TP، FP، FN، TN).", "imb_cost_sensitive"),
    ("Class weight", "وزن الفئة", "مضاعِف لخسارة أمثلة كل فئة أثناء التدريب؛ 'balanced' = n/(K·n_k).", "imb_cost_sensitive"),
    ("Focal loss", "خسارة التركيز", "−α_t(1 − p_t)^γ log p_t: تقلص وزن الأمثلة السهلة.", "imb_cost_sensitive"),
    ("Borderline-SMOTE", "SMOTE الحدودي", "SMOTE يولّد فقط من أمثلة الأقلية القريبة من الحد (DANGER).", "imb_oversampling"),
    ("ADASYN", "ADASYN", "Oversampling تكيفي: نقاط أكثر حول أمثلة الأقلية الأصعب.", "imb_oversampling"),
    ("Tomek link", "رابط تومك", "زوج من فئتين مختلفتين كل منهما أقرب جار للآخر.", "imb_undersampling"),
    ("Edited nearest neighbours", "الجيران الأقرب المحرَّرة", "حذف الأمثلة التي يخالفها جيرانها.", "imb_undersampling"),
    ("Balanced random forest", "الغابة العشوائية المتوازنة", "غابة تُدرَّب كل شجرة فيها على Bootstrap متوازن.", "imb_ensembles"),
    ("Prior shift", "تحوّل الأولوية", "تغير الانتشار بين التدريب والنشر مع ثبات P(x|y) (يسمى أيضًا Label shift).",
     "imb_probabilities"),
)
