"""Curriculum registry: the single source of truth for every page.

Navigation (core/navigation.py), page headers (core/page.py), search
(app_pages/resources/search.py), the progress tracker, the tests and
docs/curriculum.md (scripts/build_docs.py) are all generated from MODULES.
To add a module: add one Module entry here and create its page file.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Module:
    id: str
    file: str
    group: str
    title_ar: str
    title_en: str
    icon: str
    description: str
    objectives: tuple[str, ...] = ()
    prereqs: tuple[str, ...] = ()
    difficulty: str = "مبتدئ"
    minutes: int = 30
    keywords: tuple[str, ...] = ()
    dataset: str = ""
    lab: str = ""
    kind: str = "lesson"  # lesson | lab | project | resource | start
    tracked: bool = True  # counts toward progress percentage

    @property
    def label(self) -> str:
        return f"{self.title_ar} · {self.title_en}"


DIFFICULTIES = ("مبتدئ", "متوسط", "متقدم", "بحثي")

GROUPS: dict[str, str] = {
    "start": "ابدأ هنا · Start Here",
    "breiman": "فلسفة ليو بريمان · Leo Breiman's Philosophy",
    "pre_ml": "قبل تعلّم الآلة · Before ML",
    "foundations": "الرياضيات والتعلّم الإحصائي · Foundations",
    "optimization": "التحسين · Optimization",
    "supervised": "التعلّم الموجَّه · Supervised Learning",
    "trees_ensembles": "الأشجار والتجميعات · Trees & Ensembles",
    "evaluation": "التحقق والتقييم · Validation & Evaluation",
    "imbalanced": "التصنيف غير المتوازن · Imbalanced Classification",
    "tuning": "ضبط المعاملات الفائقة · Hyperparameter Tuning",
    "unsupervised": "التعلّم غير الموجَّه · Unsupervised Learning",
    "interpretability": "التفسير · Interpretability",
    "causal_ml": "التعلّم السببي وDML · Causal ML & Double ML",
    "modern": "موضوعات حديثة وجسور · Modern ML & Bridges",
    "production": "تعلّم الآلة في الإنتاج · Production ML",
    "labs": "المختبرات والأدوات · Labs & Tools",
    "projects": "المشاريع · Projects",
    "resources": "الموارد · Resources",
}

_M = Module

MODULES: tuple[Module, ...] = (
    # ================================================================== start
    _M("home", "app_pages/start/home.py", "start", "الرئيسية", "Home", ":material/home:",
       "الصفحة الرئيسية: خريطة الرحلة، مسارات التعلّم، والتقدّم.", kind="start", tracked=False,
       keywords=("roadmap", "خريطة", "بداية", "learning paths")),
    _M("course_guide", "app_pages/start/course_guide.py", "start", "دليل المقرر", "Course Guide",
       ":material/menu_book:",
       "كيف تستخدم المنصة: مستويات الشرح، قالب الخوارزمية ذو الـ27 عنصرًا، خريطة المتطلبات، ومسارات التعلّم.",
       kind="start", tracked=False, minutes=10,
       keywords=("guide", "levels", "prerequisites", "template", "دليل", "مسار")),

    # ================================================================ breiman
    _M("breiman_two_cultures", "app_pages/breiman/breiman_two_cultures.py", "breiman",
       "ليو بريمان والثقافتان في النمذجة الإحصائية", "Leo Breiman: The Two Cultures", ":material/history_edu:",
       "مقالة Breiman (2001): ثقافة نمذجة البيانات مقابل ثقافة النمذجة الخوارزمية، الدقة التنبؤية كمعيار تحقق، "
       "نقد اختبارات جودة الملاءمة، ردود Cox وEfron وHoadley وParzen، وكيف التقت الثقافتان اليوم في DML.",
       objectives=("شرح «الصندوق الأسود» الذي تنتج فيه الطبيعة y من x، وموقف كل ثقافة منه.",
                   "فهم لماذا يرى Breiman أن نجاح اختبار جودة الملاءمة لا يثبت صحة النموذج.",
                   "مقارنة نموذج بيانات (Logistic) بنموذج خوارزمي (Random Forest) على بيانات لم يرها أي منهما.",
                   "تقييم الانتقادات الموجّهة لبريمان وموقع الثقافتين في علم البيانات الحديث وDML."),
       minutes=55, lab="Two Cultures Lab",
       keywords=("breiman", "two cultures", "data modeling", "algorithmic modeling", "black box", "goodness of fit",
                 "hosmer-lemeshow", "predictive accuracy", "cox", "efron", "parzen", "بريمان", "الثقافتان", "فلسفة")),
    _M("breiman_three_lessons", "app_pages/breiman/breiman_three_lessons.py", "breiman",
       "دروس بريمان الثلاثة: Rashomon وOccam وBellman", "Rashomon, Occam & Bellman", ":material/diversity_3:",
       "تعدد النماذج الجيدة (Rashomon)، التعارض بين الدقة والبساطة (Occam)، والأبعاد الكثيرة كنعمة لا لعنة (Bellman) — "
       "مع ثلاثة مختبرات ونقاش حديث: Rashomon set وRudin وFisher وآخرين.",
       objectives=("إيجاد عدة نماذج متقاربة الدقة تختلف في المتغيرات التي «تفسّر» y.",
                   "قياس عدم استقرار الشجرة الواحدة ومقابلته بدقة الغابة وقابليتها للتفسير.",
                   "إثبات أن إضافة خصائص (Random features) قد ترفع دقة مصنّف خطي بدل أن تضرها.",
                   "تمييز ما تجاوزه البحث الحديث من آراء بريمان وما بقي صحيحًا."),
       prereqs=("breiman_two_cultures",), difficulty="متوسط", minutes=60, lab="Rashomon · Occam · Bellman Labs",
       keywords=("rashomon", "occam", "bellman", "curse of dimensionality", "multiplicity", "rashomon set",
                 "interpretability", "accuracy", "instability", "random features", "rudin", "تعدد النماذج")),
    _M("breiman_legacy", "app_pages/breiman/breiman_legacy.py", "breiman",
       "إرث بريمان: CART والتجميع والغابات", "Breiman's Legacy: CART, Bagging, Arcing & Forests",
       ":material/park:",
       "خط زمني لإسهامات Breiman: CART (1984)، ACE (1985)، Nonnegative garrote (1995)، Bagging وStacking (1996)، "
       "Arcing (1998)، Random Forests (2001) مع OOB والأهمية بالتبديل — ومختبر «الإجراءات غير المستقرة».",
       objectives=("ربط كل إسهام لبريمان بالمشكلة التي حلّها وبصفحته في المنصة.",
                   "قياس عدم الاستقرار وإثبات أن Bagging يفيد الإجراءات غير المستقرة أساسًا.",
                   "مقارنة تقدير OOB بتقدير Cross-validation.",
                   "فهم الأهمية بالتبديل (Permutation importance) كفكرة بريمانية."),
       prereqs=("breiman_three_lessons",), difficulty="متوسط", minutes=50, lab="Instability & Bagging Lab",
       keywords=("cart", "bagging", "stacking", "arcing", "random forest", "out-of-bag", "oob", "permutation importance",
                 "nonnegative garrote", "ace", "unstable", "بريمان", "إرث")),

    # ================================================================= pre_ml
    _M("what_is_ml", "app_pages/pre_ml/what_is_ml.py", "pre_ml", "ما هو تعلّم الآلة؟", "What is Machine Learning?",
       ":material/psychology:",
       "تعريف Mitchell، التعلّم من البيانات مقابل البرمجة الصريحة، ودورة حياة مشروع ML الكاملة.",
       objectives=("تعريف ML بدقة: Task وExperience وPerformance.",
                   "التمييز بين ML والإحصاء الكلاسيكي والبرمجة التقليدية.",
                   "رسم دورة حياة مشروع ML من السؤال إلى المراقبة."),
       minutes=30, keywords=("machine learning", "definition", "mitchell", "learning", "تعلم الآلة", "lifecycle")),
    _M("ml_vocabulary", "app_pages/pre_ml/ml_vocabulary.py", "pre_ml", "الخوارزمية والنموذج والمقدِّر والمعاملات",
       "Algorithm, Model, Estimator & Hyperparameters", ":material/schema:",
       "Algorithm مقابل Model مقابل Estimator، وParameters مقابل Hyperparameters مقابل solver options وruntime config.",
       objectives=("التمييز بين الخوارزمية والنموذج المُدرَّب وكائن Estimator.",
                   "التمييز بين ما يُتعلَّم من البيانات وما يُختار قبل التدريب.",
                   "قراءة واجهة scikit-learn: fit/predict/transform وget_params/set_params."),
       prereqs=("what_is_ml",), minutes=35,
       keywords=("algorithm", "model", "estimator", "parameter", "hyperparameter", "fit", "predict", "coef_",
                 "get_params", "معامل")),
    _M("prediction_vs_causality", "app_pages/pre_ml/prediction_vs_causality.py", "pre_ml",
       "التنبؤ والتفسير والسببية", "Prediction vs Explanation vs Causality", ":material/call_split:",
       "ثلاثة أسئلة مختلفة تتطلب أدوات وتقييمات مختلفة؛ لماذا لا يثبت الأداء التنبؤي علاقة سببية.",
       objectives=("صياغة السؤال: تنبؤ أم تفسير أم أثر سببي؟",
                   "فهم لماذا قد يكون المتغير الأفضل تنبؤيًا بلا أثر سببي.",
                   "معرفة متى نحتاج Causal ML وDML."),
       prereqs=("what_is_ml",), difficulty="متوسط", minutes=30,
       keywords=("prediction", "explanation", "causality", "confounding", "shmueli", "سببية", "تنبؤ")),
    _M("task_types", "app_pages/pre_ml/task_types.py", "pre_ml", "أنواع مسائل تعلّم الآلة", "ML Task Types",
       ":material/category:",
       "Regression وClassification وClustering وRanking وAnomaly detection وForecasting وأشكال الإشراف.",
       objectives=("تصنيف أي مسألة إلى نوعها الصحيح.", "ربط نوع المسألة بالمخرج والـLoss والمقياس.",
                   "التمييز بين Supervised وUnsupervised وSemi-supervised وReinforcement."),
       prereqs=("what_is_ml",), minutes=25,
       keywords=("regression", "classification", "clustering", "ranking", "anomaly", "forecasting",
                 "supervised", "unsupervised", "أنواع")),
    _M("feature_matrix", "app_pages/pre_ml/feature_matrix.py", "pre_ml", "مصفوفة الخصائص X والهدف y",
       "Feature Matrix X and Target y", ":material/table_chart:",
       "من الجدول إلى X وy: فضاء الخصائص، الأبعاد، الترميز، ومختبر Feature Space.",
       objectives=("بناء X وy بشكل صحيح من جدول خام.", "تخيّل الملاحظات كنقاط في فضاء الخصائص.",
                   "فهم أثر الترميز والقياس على الهندسة."),
       prereqs=("task_types",), minutes=35, lab="Feature Space Lab", dataset="mixed",
       keywords=("feature matrix", "target", "design matrix", "feature space", "dimension", "X", "y")),
    _M("ml_readiness", "app_pages/pre_ml/ml_readiness.py", "pre_ml", "جاهزية البيانات لتعلّم الآلة",
       "ML Readiness Checklist", ":material/fact_check:",
       "جسر من منصة علم البيانات: 13 فحصًا قبل أي نموذج — الهدف، وحدة التحليل، التوفر لحظة التنبؤ، التسرب، وغيرها.",
       objectives=("تطبيق قائمة جاهزية من 13 بندًا على أي Dataset.", "تشغيل فحص آلي وقراءة تقريره.",
                   "معرفة متى يجب العودة إلى تنظيف البيانات."),
       prereqs=("feature_matrix",), difficulty="متوسط", minutes=40, lab="ML Readiness Checker", dataset="mixed",
       keywords=("readiness", "checklist", "missing", "outliers", "imbalance", "leakage", "duplicates",
                 "unit of analysis", "جاهزية")),
    _M("baselines", "app_pages/pre_ml/baselines.py", "pre_ml", "النماذج المرجعية", "Baseline Models",
       ":material/horizontal_rule:",
       "DummyRegressor وDummyClassifier ونماذج بسيطة: كل نتيجة تُقارن بخط أساس.",
       objectives=("بناء Baseline مناسب لكل نوع مسألة.", "فهم لماذا 95% دقة قد تكون فشلًا.",
                   "استخدام Baseline لاكتشاف الأخطاء مبكرًا."),
       prereqs=("task_types",), minutes=25, dataset="imbalanced",
       keywords=("baseline", "dummy", "majority class", "mean predictor", "naive forecast", "مرجعي")),
    _M("data_splits", "app_pages/pre_ml/data_splits.py", "pre_ml", "التدريب والتحقق والاختبار",
       "Train / Validation / Test", ":material/splitscreen:",
       "أدوار الأجزاء الثلاثة، train_test_split، الطبقية، وأثر حجم مجموعة الاختبار على عدم اليقين.",
       objectives=("شرح دور كل جزء.", "تطبيق Stratified split.", "تقدير تقلب درجة الاختبار بالمحاكاة."),
       prereqs=("baselines",), minutes=30, lab="Split Lab", dataset="classification",
       keywords=("train test split", "validation", "holdout", "stratify", "test set", "تقسيم")),
    _M("leakage", "app_pages/pre_ml/leakage.py", "pre_ml", "تسرّب البيانات", "Data Leakage",
       ":material/water_drop:",
       "تسعة أنواع للتسرّب مع مختبر يعطي درجة ممتازة زائفة ثم تنهار عند تصحيح الـPipeline.",
       objectives=("تمييز أنواع التسرب التسعة.", "إعادة إنتاج نتيجة مضخّمة ثم تصحيحها.",
                   "بناء إجراءات تمنع التسرب هيكليًا."),
       prereqs=("data_splits",), difficulty="متقدم", minutes=50, lab="Leakage Lab", dataset="high_dim",
       keywords=("leakage", "target leakage", "feature selection leakage", "temporal leakage", "group leakage",
                 "target encoding", "hpo leakage", "تسرب")),
    _M("pipelines", "app_pages/pre_ml/pipelines.py", "pre_ml", "خطوط المعالجة", "Pipelines & ColumnTransformer",
       ":material/account_tree:",
       "Pipeline وColumnTransformer وfit/transform/fit_transform وأسماء step__parameter، ولماذا تمنع التسرب.",
       objectives=("بناء Pipeline كامل لبيانات مختلطة.", "فهم ما يحدث في fit مقابل transform.",
                   "ضبط معاملات داخلية بأسماء step__parameter."),
       prereqs=("leakage",), difficulty="متوسط", minutes=40, lab="Pipeline Lab", dataset="mixed",
       keywords=("pipeline", "columntransformer", "fit_transform", "make_pipeline", "step__param", "خط المعالجة")),

    # ============================================================ foundations
    _M("linear_algebra", "app_pages/foundations/linear_algebra.py", "foundations", "الجبر الخطي لتعلّم الآلة",
       "Linear Algebra for ML", ":material/grid_on:",
       "المتجهات والمصفوفات والجداء النقطي والمعايير والمسافات والرتبة والمعكوس الزائف والقيم الذاتية وSVD.",
       objectives=("ربط كل عملية جبرية بخوارزمية تستخدمها.", "حساب المسافات والتشابه وتفسيرها هندسيًا.",
                   "فهم القيم الذاتية وSVD كأساس لـPCA والانحدار."),
       prereqs=("feature_matrix",), difficulty="متوسط", minutes=60, lab="Matrix Transform Lab",
       keywords=("vector", "matrix", "dot product", "norm", "distance", "cosine", "rank", "inverse",
                 "pseudo-inverse", "eigenvalue", "svd", "جبر خطي")),
    _M("calculus", "app_pages/foundations/calculus.py", "foundations", "التفاضل لتعلّم الآلة", "Calculus for ML",
       ":material/show_chart:",
       "المشتقة والمشتقات الجزئية والتدرج وقاعدة السلسلة والنهايات العظمى والصغرى.",
       objectives=("تفسير المشتقة كميل محلي.", "حساب التدرج ورسمه على خريطة كنتورية.",
                   "فهم قاعدة السلسلة كأساس لـBackpropagation."),
       prereqs=("linear_algebra",), difficulty="متوسط", minutes=40, lab="Tangent & Gradient Lab",
       keywords=("derivative", "gradient", "partial derivative", "chain rule", "minimum", "maximum", "تفاضل")),
    _M("probability", "app_pages/foundations/probability.py", "foundations", "الاحتمالات لتعلّم الآلة",
       "Probability for ML", ":material/casino:",
       "المتغيرات العشوائية والتوقع والتباين والتغاير والاحتمال الشرطي وقاعدة Bayes والإمكان والتوزيعات.",
       objectives=("ربط Likelihood بدوال الخسارة (MSE وLog loss).", "تطبيق Bayes على مسألة تصنيف.",
                   "التعرف على التوزيعات الشائعة في ML."),
       prereqs=("calculus",), difficulty="متوسط", minutes=45, lab="Likelihood Lab",
       keywords=("probability", "expectation", "variance", "covariance", "bayes", "likelihood",
                 "distribution", "mle", "احتمال")),
    _M("statistics_ml", "app_pages/foundations/statistics_ml.py", "foundations", "الإحصاء لتعلّم الآلة",
       "Statistics for ML", ":material/functions:",
       "المجتمع والعينة والمقدِّر والتحيز والتباين والخطأ المعياري وBootstrap والارتباط والتعدد الخطي.",
       objectives=("التمييز بين تحيّز المقدِّر وتباينه.", "تطبيق Bootstrap لتقدير عدم اليقين في مقياس.",
                   "فهم أثر Multicollinearity على المعاملات."),
       prereqs=("probability",), difficulty="متوسط", minutes=45, lab="Bootstrap Lab",
       keywords=("estimator", "bias", "variance", "standard error", "bootstrap", "correlation",
                 "multicollinearity", "إحصاء")),
    _M("statistical_learning", "app_pages/foundations/statistical_learning.py", "foundations",
       "أسس التعلّم الإحصائي", "Statistical Learning Foundations", ":material/school:",
       "Empirical vs Expected risk، خطأ التدريب والتحقق، التعميم، الخطأ القابل وغير القابل للاختزال، السعة والتنظيم.",
       objectives=("صياغة التعلّم كتقليل للمخاطر التجريبية.", "تفكيك الخطأ إلى Reducible وIrreducible.",
                   "قراءة Learning curves وValidation curves."),
       prereqs=("statistics_ml",), difficulty="متوسط", minutes=50,
       keywords=("empirical risk", "expected risk", "generalization", "irreducible error", "capacity",
                 "learning curve", "validation curve", "regularization")),
    _M("bias_variance", "app_pages/foundations/bias_variance.py", "foundations", "مقايضة التحيّز والتباين",
       "Bias–Variance Trade-off", ":material/balance:",
       "تفكيك الخطأ بالمحاكاة مع Animation لدرجة كثير الحدود وعمق الشجرة: Underfitting مقابل Overfitting.",
       objectives=("قياس Bias² وVariance بالمحاكاة.", "ربط السعة بالتحيز والتباين.",
                   "التعرف على Underfitting وOverfitting من المنحنيات."),
       prereqs=("statistical_learning",), difficulty="متوسط", minutes=40, lab="Bias–Variance Lab",
       keywords=("bias", "variance", "overfitting", "underfitting", "polynomial degree", "tree depth", "تحيز")),
    _M("loss_functions", "app_pages/foundations/loss_functions.py", "foundations", "دوال الخسارة", "Loss Functions",
       ":material/trending_down:",
       "MSE وMAE وHuber وQuantile وPoisson deviance وLog loss وHinge وExponential وBrier؛ Loss vs Objective vs Metric.",
       objectives=("اختيار Loss يتوافق مع هدف المسألة.", "رؤية كيف تعاقب كل Loss الأخطاء بصريًا.",
                   "التمييز بين Loss وObjective وMetric."),
       prereqs=("statistical_learning",), difficulty="متوسط", minutes=45, lab="Loss Function Lab",
       keywords=("loss", "mse", "mae", "huber", "quantile", "pinball", "poisson", "log loss", "cross-entropy",
                 "hinge", "exponential", "brier", "objective", "metric", "خسارة")),
    _M("learning_theory", "app_pages/foundations/learning_theory.py", "foundations", "نظرية التعلّم",
       "Learning Theory", ":material/auto_stories:",
       "فضاء الفرضيات، السعة، Structural risk، حدس VC dimension، الهوامش، حدود التعميم، وNo Free Lunch.",
       objectives=("فهم لماذا يمكن التعميم من عينة محدودة.", "ربط VC dimension بالسعة وحجم العينة.",
                   "فهم حدود نظرية No Free Lunch عمليًا."),
       prereqs=("bias_variance",), difficulty="بحثي", minutes=45,
       keywords=("hypothesis space", "vc dimension", "pac", "structural risk", "generalization bound",
                 "no free lunch", "margin", "shattering")),

    # =========================================================== optimization
    _M("optimization_intro", "app_pages/optimization/optimization_intro.py", "optimization",
       "أساسيات التحسين", "Optimization Foundations", ":material/landscape:",
       "الحل المغلق مقابل التكراري، التحدّب، النهايات المحلية، ولماذا يتحول التعلّم إلى مسألة تحسين.",
       objectives=("اشتقاق الحل المغلق للمربعات الصغرى.", "التمييز بين الدوال المحدّبة وغير المحدّبة.",
                   "معرفة متى نحتاج خوارزمية تكرارية."),
       prereqs=("calculus", "loss_functions"), difficulty="متوسط", minutes=35,
       keywords=("optimization", "closed form", "normal equations", "convex", "local minimum", "تحسين")),
    _M("gradient_descent", "app_pages/optimization/gradient_descent.py", "optimization",
       "الانحدار التدرّجي وSGD", "Gradient Descent, SGD & Mini-batch", ":material/south_east:",
       "مختبر كامل: معدل التعلّم ونقطة البداية والتكرارات والضجيج ونمط الدفعات، مع منحنى الخسارة والمسار والتباعد.",
       objectives=("تنفيذ Gradient Descent من الصفر.", "مقارنة Batch وSGD وMini-batch.",
                   "تشخيص معدل تعلّم صغير جدًا أو كبير جدًا."),
       prereqs=("optimization_intro",), difficulty="متوسط", minutes=50, lab="Gradient Descent Lab",
       keywords=("gradient descent", "sgd", "mini-batch", "learning rate", "divergence", "momentum",
                 "trajectory", "contour", "انحدار تدرجي")),
    _M("advanced_optimizers", "app_pages/optimization/advanced_optimizers.py", "optimization",
       "محسّنات متقدمة", "Coordinate Descent, Newton, L-BFGS & Early Stopping", ":material/speed:",
       "Coordinate descent (Lasso)، Newton والمصفوفة الهيسية، L-BFGS، Momentum/Adam كمفهوم، والتوقف المبكر.",
       objectives=("فهم لماذا يستخدم Lasso الـCoordinate descent.", "مقارنة Newton وGD في عدد الخطوات والتكلفة.",
                   "استخدام Early stopping كتنظيم."),
       prereqs=("gradient_descent",), difficulty="متقدم", minutes=40, lab="Optimizer Race",
       keywords=("coordinate descent", "newton", "hessian", "l-bfgs", "lbfgs", "adam", "momentum",
                 "early stopping", "solver")),

    # ============================================================= supervised
    _M("linear_regression", "app_pages/supervised/linear_regression.py", "supervised", "الانحدار الخطي",
       "Linear Regression", ":material/trending_up:",
       "البسيط والمتعدد: المعادلة، المعاملات، البواقي، المربعات الصغرى، الهندسة (الإسقاط)، وافتراضات التنبؤ مقابل الاستدلال.",
       objectives=("اشتقاق OLS وتفسيره هندسيًا كإسقاط.", "تفسير المعاملات والبواقي.",
                   "التمييز بين افتراضات التنبؤ وافتراضات الاستدلال."),
       prereqs=("optimization_intro", "data_splits"), difficulty="متوسط", minutes=55, lab="OLS Lab",
       dataset="regression",
       keywords=("linear regression", "ols", "least squares", "residuals", "coefficients", "projection",
                 "LinearRegression", "انحدار خطي")),
    _M("polynomial_regression", "app_pages/supervised/polynomial_regression.py", "supervised",
       "الانحدار متعدد الحدود والأساسات", "Polynomial Regression & Basis Expansion", ":material/timeline:",
       "PolynomialFeatures وSplineTransformer: نموذج خطي في المعاملات غير خطي في المدخلات.",
       objectives=("بناء خصائص متعددة الحدود داخل Pipeline.", "رؤية Overfitting مع الدرجة العالية.",
                   "مقارنة Polynomial وSplines."),
       prereqs=("linear_regression",), difficulty="متوسط", minutes=30, lab="Degree Lab", dataset="regression",
       keywords=("polynomial", "PolynomialFeatures", "spline", "SplineTransformer", "basis expansion")),
    _M("regularization", "app_pages/supervised/regularization.py", "supervised", "التنظيم: Ridge وLasso وElastic Net",
       "Regularization: Ridge, Lasso, Elastic Net", ":material/compress:",
       "L1 وL2 وElastic Net، مسارات المعاملات، الندرة، الخصائص المترابطة، ومختبر alpha وl1_ratio.",
       objectives=("فهم هندسة قيود L1 وL2.", "قراءة Coefficient paths.",
                   "اختيار alpha بالتحقق المتقاطع."),
       prereqs=("linear_regression", "bias_variance"), difficulty="متقدم", minutes=55,
       lab="Regularization Path Lab", dataset="high_dim",
       keywords=("ridge", "lasso", "elastic net", "l1", "l2", "alpha", "l1_ratio", "sparsity",
                 "coefficient path", "RidgeCV", "LassoCV", "تنظيم")),
    _M("robust_regression", "app_pages/supervised/robust_regression.py", "supervised", "الانحدار المتين",
       "Robust Regression", ":material/shield:",
       "HuberRegressor وRANSAC وTheil-Sen وQuantileRegressor أمام القيم الشاذة.",
       objectives=("فهم أثر القيم الشاذة على OLS.", "مقارنة المقدرات المتينة.", "معرفة متى يُفضّل Quantile regression."),
       prereqs=("linear_regression", "loss_functions"), difficulty="متقدم", minutes=30, lab="Outlier Robustness Lab",
       keywords=("robust", "huber", "ransac", "theil-sen", "quantile regression", "outliers", "متين")),
    _M("classification_setup", "app_pages/supervised/classification_setup.py", "supervised", "مدخل إلى التصنيف",
       "Classification Setup", ":material/label:",
       "Binary وMulticlass (OvR/OvO/Softmax) وMultilabel وOrdinal، والدرجات مقابل الاحتمالات مقابل القرارات.",
       objectives=("التمييز بين أشكال التصنيف الأربعة.", "فهم One-vs-Rest وOne-vs-One وSoftmax.",
                   "التمييز بين score وprobability وdecision."),
       prereqs=("task_types", "probability"), minutes=30, dataset="multiclass",
       keywords=("binary", "multiclass", "multilabel", "ordinal", "one-vs-rest", "softmax", "decision_function",
                 "predict_proba", "تصنيف")),
    _M("logistic_regression", "app_pages/supervised/logistic_regression.py", "supervised", "الانحدار اللوجستي",
       "Logistic Regression", ":material/show_chart:",
       "Sigmoid والـOdds والـLog-odds وحدّ القرار وLog loss والتنظيم، مع التغييرات الحديثة في penalty/l1_ratio.",
       objectives=("اشتقاق النموذج من Log-odds.", "تفسير المعاملات كـOdds ratios.",
                   "اختيار C وl1_ratio وsolver بشكل صحيح في النسخة الحالية."),
       prereqs=("classification_setup", "loss_functions", "gradient_descent"), difficulty="متوسط", minutes=55,
       lab="Logistic Boundary Lab", dataset="classification",
       keywords=("logistic regression", "sigmoid", "odds", "log-odds", "log loss", "C", "l1_ratio", "penalty",
                 "solver", "class_weight", "LogisticRegression", "لوجستي")),
    _M("naive_bayes", "app_pages/supervised/naive_bayes.py", "supervised", "بايز الساذج", "Naive Bayes",
       ":material/percent:",
       "قاعدة Bayes والاستقلال الشرطي، ومتغيرات GaussianNB وMultinomialNB وBernoulliNB وComplementNB.",
       objectives=("اشتقاق المصنِّف من قاعدة Bayes.", "اختيار المتغير المناسب لنوع البيانات.",
                   "فهم لماذا يعمل رغم كسر الافتراض."),
       prereqs=("classification_setup", "probability"), difficulty="متوسط", minutes=35, lab="NB Lab",
       keywords=("naive bayes", "bayes theorem", "conditional independence", "GaussianNB", "MultinomialNB",
                 "BernoulliNB", "ComplementNB", "var_smoothing", "alpha")),
    _M("lda_qda", "app_pages/supervised/lda_qda.py", "supervised", "التحليل التمييزي LDA/QDA",
       "Linear & Quadratic Discriminant Analysis", ":material/donut_large:",
       "نمذجة توزيع كل فئة: التغاير المشترك مقابل المنفصل، الحدود الخطية مقابل التربيعية، الأولويات والانكماش.",
       objectives=("اشتقاق حدّ LDA الخطي.", "مقارنة LDA وQDA وLogistic.", "استخدام Shrinkage مع أبعاد عالية."),
       prereqs=("naive_bayes",), difficulty="متقدم", minutes=35, lab="LDA/QDA Boundary Lab",
       keywords=("lda", "qda", "discriminant", "covariance", "shrinkage", "priors",
                 "LinearDiscriminantAnalysis", "QuadraticDiscriminantAnalysis")),
    _M("knn", "app_pages/supervised/knn.py", "supervised", "أقرب الجيران", "k-Nearest Neighbors",
       ":material/hub:",
       "الجوار والمسافة والقياس ولعنة الأبعاد، مع مختبر k والمسافة وحدّ القرار، وتنفيذ من الصفر.",
       objectives=("تنفيذ kNN من الصفر.", "رؤية أثر k على التحيز والتباين.", "فهم لماذا القياس إلزامي."),
       prereqs=("classification_setup", "linear_algebra"), minutes=40, lab="kNN Lab", dataset="moons",
       keywords=("knn", "k-nearest neighbors", "n_neighbors", "distance", "minkowski", "weights",
                 "curse of dimensionality", "KNeighborsClassifier", "جيران")),
    _M("svm", "app_pages/supervised/svm.py", "supervised", "آلات المتجهات الداعمة", "Support Vector Machines",
       ":material/linear_scale:",
       "المستوى الفاصل والهامش والمتجهات الداعمة والهامش الصلب/اللين وHinge loss والنوى وKernel trick.",
       objectives=("اشتقاق مسألة الهامش الأقصى.", "رؤية أثر C وgamma على الحدود.",
                   "فهم Kernel trick وأنواع النوى."),
       prereqs=("logistic_regression", "knn"), difficulty="متقدم", minutes=60, lab="SVM Margin Lab", dataset="moons",
       keywords=("svm", "svc", "margin", "support vectors", "hinge", "kernel", "rbf", "gamma", "C", "kernel trick",
                 "LinearSVC")),

    # ======================================================= trees_ensembles
    _M("decision_trees", "app_pages/trees_ensembles/decision_trees.py", "trees_ensembles", "أشجار القرار",
       "Decision Trees", ":material/park:",
       "التقسيم الثنائي المتكرر، Gini والإنتروبيا والـMSE، مختبر التقسيم ومختبر التقليم ccp_alpha.",
       objectives=("حساب Impurity وInformation gain يدويًا.", "رؤية أثر max_depth وmin_samples_leaf.",
                   "تطبيق Cost-complexity pruning."),
       prereqs=("classification_setup", "bias_variance"), difficulty="متوسط", minutes=55,
       lab="Tree Split Lab + Pruning Lab", dataset="classification",
       keywords=("decision tree", "gini", "entropy", "log_loss", "information gain", "max_depth",
                 "min_samples_leaf", "ccp_alpha", "pruning", "monotonic_cst", "شجرة")),
    _M("ensemble_learning", "app_pages/trees_ensembles/ensemble_learning.py", "trees_ensembles",
       "التعلّم التجميعي", "Ensemble Learning", ":material/groups:",
       "Bagging وRandom subspace وVoting وStacking وBoosting: لماذا تتفوق المجموعة على الفرد.",
       objectives=("فهم تقليل التباين بالتجميع.", "بناء Voting وStacking.", "التمييز بين Bagging وBoosting."),
       prereqs=("decision_trees",), difficulty="متوسط", minutes=40, lab="Ensemble Builder",
       keywords=("ensemble", "bagging", "voting", "stacking", "boosting", "wisdom of crowds", "تجميع")),
    _M("random_forest", "app_pages/trees_ensembles/random_forest.py", "trees_ensembles",
       "الغابات العشوائية وExtra Trees", "Random Forest & Extra Trees", ":material/forest:",
       "Bootstrap + خصائص عشوائية + تصويت، OOB، ومقارنة Extra Trees، مع Animation من البيانات إلى التجميع.",
       objectives=("شرح مصدري العشوائية.", "استخدام OOB score كتقدير مجاني.", "ضبط max_features وn_estimators."),
       prereqs=("ensemble_learning",), difficulty="متوسط", minutes=50, lab="Random Forest Lab", dataset="classification",
       keywords=("random forest", "extra trees", "bootstrap", "oob", "max_features", "n_estimators",
                 "max_samples", "RandomForestClassifier", "غابة")),
    _M("boosting", "app_pages/trees_ensembles/boosting.py", "trees_ensembles", "التعزيز: AdaBoost وGradient Boosting",
       "Boosting: AdaBoost & Gradient Boosting", ":material/stacked_line_chart:",
       "متعلمون ضعفاء وتصحيح تسلسلي ونموذج جمعي مرحلي ومعدل التعلّم، مع مختبر مراحل التعزيز.",
       objectives=("اشتقاق Gradient boosting كنزول تدرجي في فضاء الدوال.", "رؤية التصحيح مرحلة بمرحلة.",
                   "فهم التفاعل بين learning_rate وn_estimators."),
       prereqs=("random_forest", "gradient_descent"), difficulty="متقدم", minutes=55, lab="Boosting Stage Lab",
       keywords=("boosting", "adaboost", "gradient boosting", "weak learner", "learning_rate", "shrinkage",
                 "stagewise", "GradientBoostingRegressor", "تعزيز")),
    _M("hist_gradient_boosting", "app_pages/trees_ensembles/hist_gradient_boosting.py", "trees_ensembles",
       "HistGradientBoosting", "HistGradientBoosting (scikit-learn)", ":material/bar_chart:",
       "التعزيز بالمدرجات: التقطيع إلى bins، دعم القيم المفقودة والفئوية أصليًا، والتوقف المبكر.",
       objectives=("فهم فكرة الـbinning وتسريعها.", "استخدام categorical_features ودعم NaN.",
                   "ضبط max_leaf_nodes وlearning_rate وl2_regularization."),
       prereqs=("boosting",), difficulty="متقدم", minutes=35, lab="HGB Lab", dataset="mixed",
       keywords=("HistGradientBoostingClassifier", "histogram", "bins", "max_bins", "categorical_features",
                 "early_stopping", "missing values", "max_leaf_nodes")),
    _M("xgboost", "app_pages/trees_ensembles/xgboost.py", "trees_ensembles", "XGBoost", "XGBoost",
       ":material/rocket_launch:",
       "الهدف المنظَّم، التدرجات والهيسيات، الانكماش، أخذ عينات الصفوف والأعمدة، tree_method والتوقف المبكر.",
       objectives=("اشتقاق Gain في XGBoost من التقريب التربيعي.", "فهم gamma وmin_child_weight وreg_lambda.",
                   "استخدام early stopping بشكل صحيح."),
       prereqs=("boosting",), difficulty="متقدم", minutes=50, lab="XGBoost Lab", dataset="classification",
       keywords=("xgboost", "eta", "gamma", "min_child_weight", "subsample", "colsample_bytree", "reg_alpha",
                 "reg_lambda", "tree_method", "hist", "hessian", "early_stopping_rounds")),
    _M("lightgbm", "app_pages/trees_ensembles/lightgbm.py", "trees_ensembles", "LightGBM", "LightGBM",
       ":material/bolt:",
       "التعلّم بالمدرجات والنمو حسب الورقة Leaf-wise، num_leaves وmin_data_in_leaf وfeature/bagging fraction.",
       objectives=("مقارنة Leaf-wise وLevel-wise.", "ضبط num_leaves مع max_depth بأمان.",
                   "فهم GOSS وEFB كمفاهيم."),
       prereqs=("boosting",), difficulty="متقدم", minutes=45, lab="LightGBM Lab", dataset="classification",
       keywords=("lightgbm", "num_leaves", "leaf-wise", "min_data_in_leaf", "min_child_samples", "feature_fraction",
                 "colsample_bytree", "bagging_fraction", "bagging_freq", "max_bin", "lambda_l1", "lambda_l2", "goss")),
    _M("catboost", "app_pages/trees_ensembles/catboost.py", "trees_ensembles", "CatBoost", "CatBoost",
       ":material/pets:",
       "المعالجة الأصلية للمتغيرات الفئوية، Ordered target statistics، Ordered boosting، والأشجار المتناظرة.",
       objectives=("فهم Target statistics ولماذا يجب أن تكون Ordered.", "استخدام cat_features مباشرة.",
                   "ضبط depth وl2_leaf_reg وone_hot_max_size."),
       prereqs=("boosting",), difficulty="متقدم", minutes=45, lab="CatBoost Lab", dataset="mixed",
       keywords=("catboost", "cat_features", "ordered boosting", "target statistics", "symmetric trees", "depth",
                 "l2_leaf_reg", "border_count", "one_hot_max_size", "random_strength", "bagging_temperature")),
    _M("boosting_comparison", "app_pages/trees_ensembles/boosting_comparison.py", "trees_ensembles",
       "مقارنة مكتبات التعزيز", "Boosting Comparison Lab", ":material/compare:",
       "HistGradientBoosting وXGBoost وLightGBM وCatBoost على نفس البيانات: المعالجة والدرجة والزمن والذاكرة.",
       objectives=("مقارنة المكتبات الأربع بإنصاف.", "قراءة فروق المعالجة المسبقة ودعم الفئات والقيم المفقودة.",
                   "تجنب إعلان «فائز مطلق»."),
       prereqs=("hist_gradient_boosting", "xgboost", "lightgbm", "catboost"), difficulty="متقدم", minutes=35,
       kind="lab", lab="Boosting Comparison Lab", dataset="mixed",
       keywords=("benchmark", "comparison", "xgboost vs lightgbm", "catboost", "hist gradient boosting")),

    # ============================================================= evaluation
    _M("cross_validation", "app_pages/evaluation/cross_validation.py", "evaluation", "التحقق المتقاطع",
       "Cross-Validation", ":material/view_week:",
       "KFold وStratified وRepeated وGroup وStratifiedGroup وTimeSeriesSplit وLOO وNested CV مع Animation للـFolds.",
       objectives=("اختيار المُقسِّم المطابق لبنية البيانات.", "فهم Nested CV ولماذا يلزم.",
                   "التمييز بين CV للتقييم وCross-fitting في DML."),
       prereqs=("data_splits",), difficulty="متوسط", minutes=50, lab="CV Animator", dataset="panel",
       keywords=("cross validation", "kfold", "stratifiedkfold", "groupkfold", "stratifiedgroupkfold",
                 "timeseriessplit", "repeatedkfold", "leave one out", "nested cv", "cross-fitting", "تحقق متقاطع")),
    _M("classification_metrics", "app_pages/evaluation/classification_metrics.py", "evaluation",
       "مقاييس التصنيف", "Classification Metrics", ":material/grid_4x4:",
       "مصفوفة الالتباس، Accuracy وBalanced accuracy وPrecision وRecall وSpecificity وF-beta وROC/PR وLog loss وBrier وMCC.",
       objectives=("حساب كل مقياس من مصفوفة الالتباس.", "اختيار ROC أو PR حسب الانتشار.",
                   "استخدام Metric Selector حسب التكلفة وعدم التوازن."),
       prereqs=("classification_setup", "baselines"), difficulty="متوسط", minutes=55, lab="Metric Explorer",
       dataset="imbalanced",
       keywords=("confusion matrix", "accuracy", "balanced accuracy", "precision", "recall", "specificity", "f1",
                 "f-beta", "roc", "auc", "precision-recall", "average precision", "log loss", "brier", "mcc", "مقاييس")),
    _M("regression_metrics", "app_pages/evaluation/regression_metrics.py", "evaluation", "مقاييس الانحدار",
       "Regression Metrics", ":material/straighten:",
       "MAE وMSE وRMSE وR² وAdjusted R² وحدود MAPE وRMSLE ومقاييس Deviance.",
       objectives=("اختيار المقياس حسب وحدة الخطأ وتكلفته.", "فهم متى يكون R² مضللًا.",
                   "معرفة مشكلات MAPE قرب الصفر."),
       prereqs=("linear_regression", "loss_functions"), minutes=35, lab="Residual Explorer", dataset="regression",
       keywords=("mae", "mse", "rmse", "r2", "adjusted r2", "mape", "rmsle", "deviance", "d2", "residuals")),
    _M("threshold_tuning", "app_pages/evaluation/threshold_tuning.py", "evaluation", "ضبط عتبة القرار",
       "Decision Threshold Tuning", ":material/tune:",
       "0.5 ليست قاعدة مقدسة: شريط العتبة وTP/FP/FN/TN وتكلفة الأعمال، وTunedThresholdClassifierCV.",
       objectives=("ربط العتبة بتكلفة الأخطاء.", "استخدام TunedThresholdClassifierCV دون لمس Test.",
                   "التمييز بين ضبط العتبة ومعايرة الاحتمالات."),
       prereqs=("classification_metrics",), difficulty="متوسط", minutes=35, lab="Threshold Lab", dataset="imbalanced",
       keywords=("threshold", "cutoff", "TunedThresholdClassifierCV", "FixedThresholdClassifier", "cost",
                 "business metric", "عتبة")),
    _M("calibration", "app_pages/evaluation/calibration.py", "evaluation", "معايرة الاحتمالات",
       "Probability Calibration", ":material/tune:",
       "Reliability diagram وBrier score وSigmoid (Platt) وIsotonic وTemperature scaling في CalibratedClassifierCV.",
       objectives=("قراءة Reliability diagram.", "مقارنة sigmoid وisotonic وtemperature.",
                   "معرفة أي النماذج تحتاج معايرة."),
       prereqs=("classification_metrics",), difficulty="متقدم", minutes=40, lab="Calibration Lab",
       dataset="classification",
       keywords=("calibration", "reliability diagram", "brier", "platt", "sigmoid", "isotonic", "temperature scaling",
                 "CalibratedClassifierCV", "calibration_curve", "معايرة")),
    _M("feature_selection", "app_pages/evaluation/feature_selection.py", "evaluation", "اختيار الخصائص",
       "Feature Selection", ":material/filter_alt:",
       "Filter وWrapper وEmbedded: VarianceThreshold، الاختيار أحادي المتغير، Mutual information، RFE/RFECV، L1، الأهميات.",
       objectives=("مقارنة عائلات الاختيار الثلاث.", "إجراء الاختيار داخل CV.", "قراءة منحنى RFECV."),
       prereqs=("leakage", "regularization"), difficulty="متقدم", minutes=40, lab="Selection Lab", dataset="high_dim",
       keywords=("feature selection", "variance threshold", "selectkbest", "mutual information", "rfe", "rfecv",
                 "selectfrommodel", "l1", "sequentialfeatureselector", "اختيار الخصائص")),
    _M("conformal_prediction", "app_pages/evaluation/conformal_prediction.py", "evaluation",
       "التنبؤ المطابق وعدم اليقين", "Conformal Prediction & Uncertainty", ":material/straighten:",
       "إضافة من البحث الحديث: فترات تنبؤ بتغطية مضمونة دون افتراضات توزيعية (Split conformal) من الصفر.",
       objectives=("بناء فترة Split conformal لأي نموذج.", "التحقق من التغطية بالمحاكاة.",
                   "فهم افتراض القابلية للتبادل وحدوده."),
       prereqs=("regression_metrics", "data_splits"), difficulty="بحثي", minutes=35, lab="Conformal Coverage Lab",
       dataset="regression",
       keywords=("conformal prediction", "prediction interval", "coverage", "exchangeability", "uncertainty",
                 "split conformal", "quantile", "مطابق")),

    # ============================================================= imbalanced
    _M("imbalanced", "app_pages/imbalanced/imbalanced.py", "imbalanced", "التعلّم مع البيانات غير المتوازنة: نظرة عامة",
       "Imbalanced Learning: Overview", ":material/balance:",
       "خريطة المسار: الانتشار، الطبقية، أوزان الفئات والعينات، العتبة، Undersampling وOversampling وSMOTE داخل الـPipeline.",
       objectives=("مقارنة الاستراتيجيات على نفس البيانات.", "إجراء Resampling داخل CV فقط.",
                   "اختيار مقياس لا يخدعه عدم التوازن."),
       prereqs=("classification_metrics", "threshold_tuning"), difficulty="متوسط", minutes=45, lab="Imbalance Lab",
       dataset="imbalanced",
       keywords=("imbalanced", "class_weight", "sample_weight", "smote", "undersampling", "oversampling",
                 "imbalanced-learn", "prevalence", "عدم توازن")),
    _M("imb_nature", "app_pages/imbalanced/imb_nature.py", "imbalanced", "طبيعة عدم التوازن ولماذا تفشل النماذج",
       "The Nature of Class Imbalance", ":material/pie_chart:",
       "نسبة عدم التوازن IR، الندرة المطلقة مقابل النسبية، التداخل، الجزر الصغيرة (Small disjuncts)، الضجيج، "
       "وقاعدة بايز: لماذا تنحاز الحدود نحو الأغلبية.",
       objectives=("قياس IR والتمييز بين الندرة المطلقة والنسبية.",
                   "رؤية أثر التداخل والجزر الصغيرة على الحد الفاصل.",
                   "اشتقاق كيف يدفع الانتشار عتبة بايز ولماذا ينهار Recall عند 0.5."),
       prereqs=("imbalanced",), difficulty="متوسط", minutes=40, lab="Imbalance Geometry Lab",
       keywords=("imbalance ratio", "IR", "absolute rarity", "overlap", "small disjuncts", "bayes rule", "prior",
                 "label noise", "ندرة", "تداخل")),
    _M("imb_metrics", "app_pages/imbalanced/imb_metrics.py", "imbalanced", "مقاييس التصنيف غير المتوازن",
       "Metrics for Imbalanced Classification", ":material/leaderboard:",
       "لماذا تخدع Accuracy؛ ROC مقابل PR عند تغيّر الانتشار؛ MCC وG-mean وF-beta وBalanced accuracy؛ "
       "فترات ثقة Bootstrap حين تكون الموجبات قليلة.",
       objectives=("إثبات أن ROC-AUC ثابت بينما PR-AUC ينهار مع انخفاض الانتشار.",
                   "حساب MCC وG-mean وF2 واختيار المقياس حسب الكلفة.",
                   "تقدير عدم اليقين في المقياس بعدد موجبات صغير."),
       prereqs=("imb_nature", "classification_metrics"), difficulty="متوسط", minutes=50, lab="Prevalence Lab",
       dataset="imbalanced",
       keywords=("pr-auc", "average precision", "roc-auc", "mcc", "g-mean", "f-beta", "f2", "balanced accuracy",
                 "prevalence", "bootstrap", "confidence interval", "مقاييس")),
    _M("imb_cost_sensitive", "app_pages/imbalanced/imb_cost_sensitive.py", "imbalanced", "التعلّم الحساس للتكلفة",
       "Cost-Sensitive Learning", ":material/payments:",
       "مصفوفة التكلفة، العتبة المثلى لـElkan، class_weight وsample_weight كخسارة موزونة، Focal loss، "
       "وإعادة الوزن مقابل تحريك العتبة.",
       objectives=("اشتقاق t* = C_FP / (C_FP + C_FN) وتطبيقه.",
                   "إثبات أن class_weight يعادل خسارة موزونة ويحرّك الاحتمالات.",
                   "مقارنة إعادة الوزن وتحريك العتبة على منحنى التكلفة المتوقعة."),
       prereqs=("imb_metrics", "threshold_tuning"), difficulty="متقدم", minutes=50, lab="Cost Lab",
       dataset="imbalanced",
       keywords=("cost matrix", "cost-sensitive", "elkan", "class_weight", "sample_weight", "focal loss",
                 "threshold moving", "expected cost", "تكلفة")),
    _M("imb_oversampling", "app_pages/imbalanced/imb_oversampling.py", "imbalanced", "عائلة Oversampling وSMOTE",
       "Oversampling: ROS, SMOTE & Variants", ":material/add_circle:",
       "RandomOverSampler (مع shrinkage)، SMOTE، Borderline-SMOTE 1/2، SVMSMOTE، ADASYN، KMeansSMOTE، "
       "وSMOTENC/SMOTEN للبيانات الفئوية — بصريًا وبالمقارنة داخل CV.",
       objectives=("رؤية أين يولّد كل متغيّر نقاطه ولماذا.",
                   "اختيار SMOTENC للبيانات المختلطة وSMOTEN للفئوية.",
                   "معرفة متى يضر Oversampling (التداخل والضجيج)."),
       prereqs=("imb_metrics",), difficulty="متقدم", minutes=55, lab="Sampler Visualizer",
       keywords=("oversampling", "random oversampling", "shrinkage", "smote", "borderline-smote", "svmsmote", "adasyn",
                 "kmeanssmote", "smotenc", "smoten", "synthetic")),
    _M("imb_undersampling", "app_pages/imbalanced/imb_undersampling.py", "imbalanced",
       "Undersampling والتنظيف والطرق الهجينة", "Undersampling, Cleaning & Hybrids", ":material/remove_circle:",
       "RandomUnderSampler، NearMiss 1/2/3، ClusterCentroids، Tomek links، ENN/RENN/AllKNN، CNN، OSS، NCR، "
       "Instance hardness، والهجين SMOTEENN وSMOTETomek.",
       objectives=("التمييز بين الحذف العشوائي والحذف الموجَّه والتنظيف.",
                   "رؤية ما يحذفه كل أسلوب من الأغلبية.",
                   "تركيب Oversampling مع تنظيف في طريقة هجينة."),
       prereqs=("imb_oversampling",), difficulty="متقدم", minutes=50, lab="Sampler Visualizer",
       keywords=("undersampling", "nearmiss", "tomek links", "enn", "edited nearest neighbours", "cnn",
                 "one-sided selection", "neighbourhood cleaning rule", "cluster centroids", "instance hardness",
                 "smoteenn", "smotetomek")),
    _M("imb_ensembles", "app_pages/imbalanced/imb_ensembles.py", "imbalanced", "التجميعات المتوازنة",
       "Balanced Ensembles", ":material/forest:",
       "BalancedRandomForest وBalancedBagging وEasyEnsemble وRUSBoost مقابل RF بـclass_weight='balanced_subsample' "
       "وHistGradientBoosting — بطاقات، معاملات موثقة، ومقارنة.",
       objectives=("شرح كيف يدمج كل تجميع إعادة العيّنة داخل كل مكوّن.",
                   "قراءة القيم الافتراضية الحالية (مثل bootstrap=False في BalancedRandomForest).",
                   "مقارنة التجميعات المتوازنة بالبدائل البسيطة بإنصاف."),
       prereqs=("imb_undersampling", "random_forest"), difficulty="متقدم", minutes=55, lab="Balanced Ensemble Lab",
       dataset="imbalanced",
       keywords=("balanced random forest", "balanced bagging", "easyensemble", "rusboost", "balanced_subsample",
                 "ensemble", "imbalanced-learn", "تجميع متوازن")),
    _M("imb_probabilities", "app_pages/imbalanced/imb_probabilities.py", "imbalanced",
       "الاحتمالات والمعايرة وتحوّل الانتشار", "Probabilities, Calibration & Prior Shift", ":material/percent:",
       "ما تفعله إعادة الموازنة بالاحتمالات، تصحيح الأولوية، معايرة ما بعد الموازنة، وتقدير انتشار جديد مجهول "
       "بخوارزمية EM لـSaerens وآخرين.",
       objectives=("قياس فقدان المعايرة بعد Resampling أو class_weight.",
                   "تطبيق تصحيح الأولوية واستعادة المعايرة.",
                   "تقدير الانتشار في بيانات نشر بلا تسميات."),
       prereqs=("imb_oversampling", "calibration"), difficulty="بحثي", minutes=50, lab="Prior Shift Lab",
       dataset="imbalanced",
       keywords=("calibration", "prior shift", "label shift", "saerens", "em", "prevalence estimation",
                 "quantification", "brier", "reliability", "معايرة")),
    _M("imb_multiclass_extreme", "app_pages/imbalanced/imb_multiclass_extreme.py", "imbalanced",
       "عدم التوازن متعدد الفئات والندرة القصوى", "Multi-class & Extreme Imbalance", ":material/scatter_plot:",
       "sampling_strategy كقاموس، Macro مقابل Weighted، ومتى تصبح المسألة اكتشاف شذوذ (IsolationForest) بدل تصنيف.",
       objectives=("ضبط Resampling لكل فئة في مسألة متعددة الفئات.",
                   "قراءة Macro-F1 والـRecall لكل فئة.",
                   "مقارنة التصنيف واكتشاف الشذوذ حين تكون الموجبات بالعشرات."),
       prereqs=("imb_metrics", "anomaly_detection"), difficulty="متقدم", minutes=45, lab="Extreme Rarity Lab",
       keywords=("multiclass", "macro", "weighted", "sampling_strategy", "extreme imbalance", "anomaly detection",
                 "isolation forest", "one-class", "rare events", "متعدد الفئات")),
    _M("imb_workflow", "app_pages/imbalanced/imb_workflow.py", "imbalanced", "منهجية متكاملة ومختبر مقارنة",
       "Imbalanced Workflow & Benchmark Lab", ":material/checklist:",
       "دليل قرار من 10 خطوات، ومختبر يقارن أي تركيبة (نموذج × استراتيجية) بـRepeated stratified CV "
       "على 13 مقياسًا مع سجل تجارب.",
       objectives=("اتباع بروتوكول تقييم صحيح من التقسيم إلى التقرير.",
                   "مقارنة التركيبات بإنصاف على نفس الطيات.",
                   "كتابة تقرير يذكر الانتشار ونقطة التشغيل وعدم اليقين."),
       prereqs=("imb_ensembles", "imb_probabilities"), difficulty="متقدم", minutes=60, lab="Imbalanced Benchmark Lab",
       dataset="imbalanced",
       keywords=("workflow", "benchmark", "protocol", "repeated stratified cv", "report", "decision guide",
                 "منهجية", "مختبر")),

    # ================================================================= tuning
    _M("hpo_foundations", "app_pages/tuning/hpo_foundations.py", "tuning", "أساسيات ضبط المعاملات الفائقة",
       "Hyperparameter Optimization Foundations", ":material/tune:",
       "فضاء البحث والمحاولة والهدف والميزانية، Grid وRandom وSuccessive Halving وHyperband، وNested CV.",
       objectives=("تصميم فضاء بحث معقول (خطي/لوغاريتمي).", "مقارنة Grid وRandom بنفس الميزانية.",
                   "فهم Successive halving وتسرّب HPO."),
       prereqs=("cross_validation", "ml_vocabulary"), difficulty="متوسط", minutes=45, lab="Search Strategy Lab",
       keywords=("hyperparameter optimization", "hpo", "grid search", "random search", "GridSearchCV",
                 "RandomizedSearchCV", "HalvingGridSearchCV", "successive halving", "hyperband", "search space",
                 "budget", "nested cv", "ضبط")),
    _M("bayesian_optimization", "app_pages/tuning/bayesian_optimization.py", "tuning",
       "التحسين البايزي وOptuna", "Bayesian Optimization & Optuna", ":material/auto_graph:",
       "Surrogate وAcquisition، Study وTrial وsuggest_*، TPE وRandom وCMA-ES وGP وQMC، والـPruners، مع مختبر HPO.",
       objectives=("فهم حلقة Surrogate→Acquisition→Evaluate.", "كتابة Objective لـOptuna داخل CV.",
                   "قراءة تاريخ المحاولات وخطر فرط ملاءمة التحقق."),
       prereqs=("hpo_foundations",), difficulty="متقدم", minutes=50, lab="HPO / Optuna Lab", dataset="classification",
       keywords=("bayesian optimization", "optuna", "study", "trial", "tpe", "TPESampler", "cmaes", "GPSampler",
                 "QMCSampler", "pruner", "median pruner", "hyperband", "suggest_float", "multi-objective")),
    _M("hyperparameter_encyclopedia", "app_pages/tuning/hyperparameter_encyclopedia.py", "tuning",
       "موسوعة المعاملات الفائقة", "Hyperparameter Encyclopedia", ":material/menu_book:",
       "موسوعة قابلة للبحث: المعنى والقيمة الافتراضية المتحقَّق منها والمدى والأثر والتفاعلات والتكلفة لكل معامل.",
       objectives=("إيجاد أي معامل ومعناه بسرعة.", "قراءة أثر الزيادة والنقصان وخطر Overfitting.",
                   "التحقق من القيمة الافتراضية مقابل النسخة المثبتة."),
       prereqs=("hpo_foundations",), minutes=20, kind="resource", tracked=False,
       keywords=("hyperparameter", "encyclopedia", "default", "range", "موسوعة", "معاملات")),

    # =========================================================== unsupervised
    _M("kmeans", "app_pages/unsupervised/kmeans.py", "unsupervised", "K-Means", "K-Means Clustering",
       ":material/bubble_chart:",
       "خوارزمية Lloyd خطوة بخطوة مع Animation كامل، k-means++، Inertia وSilhouette واختيار k.",
       objectives=("تنفيذ K-Means من الصفر.", "مشاهدة تحرك المراكز وتقارب الخوارزمية.",
                   "اختيار k بأدلة متعددة ومعرفة حدود K-Means."),
       prereqs=("linear_algebra", "task_types"), difficulty="متوسط", minutes=45, lab="K-Means Lab", dataset="blobs",
       keywords=("kmeans", "k-means", "lloyd", "k-means++", "inertia", "silhouette", "elbow", "n_clusters", "تجميع")),
    _M("hierarchical", "app_pages/unsupervised/hierarchical.py", "unsupervised", "التجميع الهرمي",
       "Hierarchical Clustering", ":material/account_tree:",
       "Agglomerative وأنواع الربط (ward/complete/average/single) والـDendrogram.",
       objectives=("قراءة Dendrogram.", "مقارنة طرق الربط.", "قطع الشجرة عند مستوى مناسب."),
       prereqs=("kmeans",), difficulty="متوسط", minutes=30, lab="Linkage Lab", dataset="blobs",
       keywords=("hierarchical", "agglomerative", "dendrogram", "ward", "linkage", "single", "complete", "هرمي")),
    _M("dbscan", "app_pages/unsupervised/dbscan.py", "unsupervised", "DBSCAN وHDBSCAN", "DBSCAN & HDBSCAN",
       ":material/scatter_plot:",
       "التجميع حسب الكثافة: النقاط المركزية والحدودية والضجيج، eps وmin_samples مع Animation، وHDBSCAN.",
       objectives=("فهم تعريف الكثافة في DBSCAN.", "ضبط eps بمنحنى k-distance.", "مقارنة DBSCAN وHDBSCAN."),
       prereqs=("kmeans",), difficulty="متقدم", minutes=40, lab="DBSCAN Lab", dataset="moons",
       keywords=("dbscan", "hdbscan", "density", "eps", "min_samples", "core point", "noise", "كثافة")),
    _M("gmm", "app_pages/unsupervised/gmm.py", "unsupervised", "نماذج الخليط الغاوسي", "Gaussian Mixture Models",
       ":material/blur_on:",
       "التجميع الاحتمالي وخوارزمية EM وأنواع التغاير واختيار عدد المكونات بـBIC/AIC.",
       objectives=("فهم E-step وM-step.", "مقارنة GMM وK-Means.", "استخدام BIC لاختيار عدد المكونات."),
       prereqs=("kmeans", "probability"), difficulty="متقدم", minutes=35, lab="EM Lab", dataset="blobs",
       keywords=("gmm", "gaussian mixture", "em algorithm", "covariance_type", "bic", "aic", "soft clustering")),
    _M("pca", "app_pages/unsupervised/pca.py", "unsupervised", "تحليل المكونات الرئيسية", "Principal Component Analysis",
       ":material/compress:",
       "التغاير والمتجهات الذاتية والصلة بـSVD والتباين المفسَّر والتحميلات والدرجات، مع تنفيذ من الصفر ومختبر.",
       objectives=("اشتقاق PCA من تعظيم التباين.", "تنفيذ PCA عبر SVD من الصفر.", "قراءة Scree plot وBiplot."),
       prereqs=("linear_algebra", "statistics_ml"), difficulty="متقدم", minutes=50, lab="PCA Lab", dataset="high_dim",
       keywords=("pca", "principal components", "eigenvectors", "svd", "explained variance", "loadings", "scores",
                 "scree", "whiten", "مكونات رئيسية")),
    _M("manifold", "app_pages/unsupervised/manifold.py", "unsupervised", "تقليل الأبعاد غير الخطي",
       "Kernel PCA, NMF, t-SNE & UMAP", ":material/gesture:",
       "Kernel PCA وNMF وt-SNE (perplexity وlearning_rate) وUMAP الاختياري، وحدود تفسير الخرائط.",
       objectives=("معرفة متى يفشل PCA الخطي.", "ضبط perplexity وفهم أثرها.", "تجنب قراءة المسافات العالمية في t-SNE."),
       prereqs=("pca",), difficulty="متقدم", minutes=40, lab="Embedding Lab", dataset="circles",
       keywords=("kernel pca", "nmf", "t-sne", "tsne", "umap", "perplexity", "manifold", "embedding")),
    _M("anomaly_detection", "app_pages/unsupervised/anomaly_detection.py", "unsupervised", "اكتشاف الشذوذ",
       "Anomaly Detection", ":material/troubleshoot:",
       "Isolation Forest وLOF وOne-Class SVM وElliptic Envelope؛ الفرق بين Outlier وAnomaly وNovelty وData error وRare event.",
       objectives=("التمييز بين المفاهيم الخمسة.", "مقارنة الخوارزميات الأربع على نفس البيانات.",
                   "ضبط contamination وتفسير النتائج بحذر."),
       prereqs=("dbscan",), difficulty="متقدم", minutes=40, lab="Anomaly Lab", dataset="anomalies",
       keywords=("anomaly", "outlier", "novelty", "isolation forest", "lof", "local outlier factor", "one-class svm",
                 "elliptic envelope", "contamination", "شذوذ")),

    # ======================================================= interpretability
    _M("model_inspection", "app_pages/interpretability/model_inspection.py", "interpretability",
       "فحص النماذج وأهمية الخصائص", "Model Inspection & Feature Importance", ":material/search_insights:",
       "المعاملات، Impurity importance وتحيّزها، Permutation importance، وحدّ القرار ومنحنيات التعلّم.",
       objectives=("مقارنة طرق الأهمية وحدودها.", "حساب Permutation importance على بيانات التحقق.",
                   "فهم أثر الخصائص المترابطة."),
       prereqs=("random_forest", "cross_validation"), difficulty="متقدم", minutes=40, lab="Feature Importance Lab",
       dataset="regression",
       keywords=("feature importance", "permutation importance", "impurity", "mdi", "coefficients", "inspection",
                 "learning curve", "validation curve", "أهمية")),
    _M("pdp_ice", "app_pages/interpretability/pdp_ice.py", "interpretability", "PDP وICE",
       "Partial Dependence & ICE", ":material/ssid_chart:",
       "الاعتماد الجزئي والتوقعات الشرطية الفردية، التفاعلات، وخطر الاستقراء خارج التوزيع.",
       objectives=("قراءة PDP وICE.", "اكتشاف التفاعلات من تباعد منحنيات ICE.", "معرفة حدود PDP مع الترابط."),
       prereqs=("model_inspection",), difficulty="متقدم", minutes=30, lab="PDP/ICE Lab", dataset="regression",
       keywords=("partial dependence", "pdp", "ice", "individual conditional expectation", "interaction",
                 "PartialDependenceDisplay")),
    _M("shap", "app_pages/interpretability/shap.py", "interpretability", "قيم SHAP وLIME", "SHAP Values & LIME",
       ":material/bar_chart_4_bars:",
       "قيم Shapley، التفسير العام والمحلي، TreeSHAP، تحذيرات الخصائص المترابطة والخلفية، والأهمية ≠ أثر سببي.",
       objectives=("فهم قيم Shapley وخاصية الجمع.", "قراءة Waterfall وBeeswarm.", "تجنب التفسير السببي للأهمية."),
       prereqs=("model_inspection",), difficulty="بحثي", minutes=40, lab="SHAP Lab", dataset="regression",
       keywords=("shap", "shapley", "treeshap", "lime", "local explanation", "waterfall", "beeswarm", "background data")),

    # ============================================================== causal_ml
    _M("causal_foundations", "app_pages/causal_ml/causal_foundations.py", "causal_ml", "أسس الاستدلال السببي",
       "Causal Inference Foundations", ":material/device_hub:",
       "المعالجة والنتيجة والمتغيرات المربكة والنتائج الكامنة والواقع المضاد وATE وATT وCATE والتداخل وعدم الإرباك.",
       objectives=("صياغة سؤال سببي بإطار Potential outcomes.", "تعريف ATE وATT وCATE.",
                   "فهم Overlap وUnconfoundedness ولماذا لا يثبتها التنبؤ."),
       prereqs=("prediction_vs_causality", "statistics_ml"), difficulty="متقدم", minutes=55, lab="Confounding Lab",
       dataset="causal",
       keywords=("causal inference", "treatment", "outcome", "confounder", "potential outcomes", "counterfactual",
                 "ate", "att", "cate", "overlap", "positivity", "unconfoundedness", "dag", "سببي")),
    _M("dml_core", "app_pages/causal_ml/dml_core.py", "causal_ml", "الفكرة الجوهرية في DML",
       "The Core Idea of Double ML", ":material/lightbulb:",
       "ست خطوات: دوال الإزعاج بـML، الدرجة المتعامدة، تقسيم العينة، Cross-fitting، التقدير، والاستدلال؛ وتحيّز التنظيم.",
       objectives=("شرح لماذا يفشل «ML + OLS» الساذج.", "تلخيص خطوات DML الست.",
                   "فهم مصدري التحيز: Regularization وOverfitting."),
       prereqs=("causal_foundations", "regularization", "cross_validation"), difficulty="متقدم", minutes=50,
       lab="Naive vs DML Lab", dataset="dml_nonlinear",
       keywords=("double machine learning", "dml", "debiased", "nuisance", "regularization bias", "chernozhukov",
                 "frisch-waugh-lovell", "fwl", "partialling out")),
    _M("neyman_orthogonality", "app_pages/causal_ml/neyman_orthogonality.py", "causal_ml", "تعامد Neyman",
       "Neyman Orthogonality", ":material/architecture:",
       "الدرجة ψ(W;θ,η)، شرط العزم، مشتقة Gateaux، ولماذا يقلّل التعامد الحساسية من الرتبة الأولى لأخطاء الإزعاج.",
       objectives=("كتابة الدرجة المتعامدة لـPLR.", "التحقق من التعامد تحليليًا وعدديًا.",
                   "فهم شرط معدل n^{-1/4} للإزعاج."),
       prereqs=("dml_core",), difficulty="بحثي", minutes=45, lab="Orthogonality Sensitivity Lab",
       keywords=("neyman orthogonality", "orthogonal score", "moment condition", "gateaux derivative", "psi",
                 "nuisance", "rate condition", "تعامد")),
    _M("cross_fitting", "app_pages/causal_ml/cross_fitting.py", "causal_ml", "Cross-Fitting",
       "Sample Splitting & Cross-Fitting", ":material/sync_alt:",
       "Animation كامل: الطيات، تدريب الإزعاج على المكمّل، تنبؤات خارج الطية، الدرجة، والتجميع؛ والفرق عن CV.",
       objectives=("تتبع Cross-fitting خطوة بخطوة.", "التمييز بين Cross-validation وCross-fitting.",
                   "فهم DML1 مقابل DML2 وتكرار التقسيم."),
       prereqs=("dml_core",), difficulty="متقدم", minutes=40, lab="DML Cross-Fitting Lab", dataset="dml_nonlinear",
       keywords=("cross-fitting", "sample splitting", "out-of-fold", "dml1", "dml2", "n_folds", "n_rep")),
    _M("plr", "app_pages/causal_ml/plr.py", "causal_ml", "النموذج الخطي الجزئي PLR",
       "Partially Linear Regression (PLR)", ":material/linear_scale:",
       "Y = Dθ₀ + g₀(X) + ζ وD = m₀(X) + V: تقدير g وm، البواقي، الانحدار على البواقي، مع مختبر التحييد.",
       objectives=("تنفيذ PLR من الصفر مع Cross-fitting.", "مقارنة درجتي partialling-out وIV-type.",
                   "مطابقة النتيجة مع DoubleMLPLR."),
       prereqs=("cross_fitting", "neyman_orthogonality"), difficulty="متقدم", minutes=55,
       lab="PLR Residualization Lab", dataset="dml_nonlinear",
       keywords=("plr", "partially linear", "DoubleMLPLR", "residualization", "partialling out", "iv-type",
                 "ml_l", "ml_m", "ml_g")),
    _M("pliv", "app_pages/causal_ml/pliv.py", "causal_ml", "PLIV: المتغيرات الأداتية الخطية الجزئية",
       "Partially Linear IV (PLIV)", ":material/alt_route:",
       "الداخلية، الأداة، الصلة والاستبعاد، ثم PLIV-DML مع مختبر أداة قوية مقابل ضعيفة.",
       objectives=("شرح الداخلية وشروط الأداة.", "تقدير PLIV بالتحييد.", "رؤية أثر الأداة الضعيفة."),
       prereqs=("plr",), difficulty="بحثي", minutes=45, lab="Weak Instrument Lab",
       keywords=("pliv", "instrumental variables", "endogeneity", "instrument", "relevance", "exclusion",
                 "DoubleMLPLIV", "weak instrument", "أداة")),
    _M("irm", "app_pages/causal_ml/irm.py", "causal_ml", "IRM: نموذج الانحدار التفاعلي", "Interactive Regression Model (IRM)",
       ":material/join_inner:",
       "المعالجة الثنائية، درجة الميل، انحدارات النتيجة، ATE وATT بدرجة AIPW، والتداخل والتقليم.",
       objectives=("كتابة درجة AIPW/Doubly robust.", "تشخيص التداخل عبر توزيع درجة الميل.",
                   "تقدير ATE وATT مع DoubleMLIRM."),
       prereqs=("plr", "calibration"), difficulty="بحثي", minutes=50, lab="Overlap Lab", dataset="causal",
       keywords=("irm", "interactive regression", "propensity score", "aipw", "doubly robust", "ate", "att",
                 "overlap", "trimming", "DoubleMLIRM")),
    _M("iivm", "app_pages/causal_ml/iivm.py", "causal_ml", "IIVM: نموذج IV التفاعلي", "Interactive IV Model (IIVM)",
       ":material/merge_type:",
       "أداة ثنائية ومعالجة ثنائية: LATE، المطيعون، الرتابة، والشروط التعريفية.",
       objectives=("تعريف LATE والمطيعين.", "شرح شرط الرتابة.", "تقدير LATE بـDoubleMLIIVM."),
       prereqs=("irm", "pliv"), difficulty="بحثي", minutes=40, lab="LATE Lab",
       keywords=("iivm", "late", "compliers", "monotonicity", "binary instrument", "DoubleMLIIVM", "wald")),
    _M("dml_learners", "app_pages/causal_ml/dml_learners.py", "causal_ml", "متعلمو الإزعاج وضبطهم",
       "Nuisance Learners & DML Tuning", ":material/model_training:",
       "Lasso وRF وGB وXGBoost وLightGBM كمتعلمي إزعاج، الضبط بـinner CV، التكلفة الحسابية، وتجنب التسرب.",
       objectives=("اختيار متعلمي الإزعاج ومقارنتهم.", "ضبطهم داخل كل طية دون تسرب.",
                   "فهم لماذا الدقة التنبؤية للإزعاج ليست ضمانًا."),
       prereqs=("plr", "hpo_foundations"), difficulty="بحثي", minutes=40, lab="Learner Comparison Lab",
       dataset="dml_nonlinear",
       keywords=("nuisance learners", "tuning", "inner cv", "lasso", "random forest", "lightgbm", "xgboost",
                 "nuisance loss", "stacking")),
    _M("hte", "app_pages/causal_ml/hte.py", "causal_ml", "الآثار غير المتجانسة CATE/GATE",
       "Heterogeneous Treatment Effects", ":material/scatter_plot:",
       "CATE وGATE وBLP، Meta-learners (S/T/X/R/DR)، وCausal Forest، مع رسوم لتوزيع الأثر.",
       objectives=("التمييز بين ATE وGATE وCATE.", "بناء DR-learner من الصفر.",
                   "تفسير الأثر غير المتجانس بحذر إحصائي."),
       prereqs=("irm",), difficulty="بحثي", minutes=50, lab="CATE Lab", dataset="causal",
       keywords=("cate", "gate", "blp", "heterogeneous", "meta-learner", "s-learner", "t-learner", "x-learner",
                 "r-learner", "dr-learner", "causal forest", "CausalForestDML", "econml")),
    _M("doubleml_package", "app_pages/causal_ml/doubleml_package.py", "causal_ml", "حزمة DoubleML والمكتبات",
       "DoubleML, EconML & DoWhy", ":material/inventory_2:",
       "الفئات الحالية في DoubleML (متحقَّق منها)، DoubleMLData، fit/confint/bootstrap، ومقارنة مع EconML وDoWhy.",
       objectives=("استخدام واجهة DoubleML الحالية بشكل صحيح.", "اختيار المكتبة المناسبة للسؤال.",
                   "إعداد التقرير القابل لإعادة الإنتاج."),
       prereqs=("plr", "irm"), difficulty="متقدم", minutes=40, lab="DoubleML Runner",
       keywords=("doubleml", "econml", "dowhy", "pywhy", "DoubleMLData", "confint", "bootstrap", "library")),
    _M("panel_did", "app_pages/causal_ml/panel_did.py", "causal_ml", "Panel وفروق الفروق مع DML",
       "Panel Data & DiD with DML", ":material/calendar_view_month:",
       "بنية Panel، التوقيت المتدرج، ATT(g,t)، المجموعات غير المعالجة أبدًا، التوقع المسبق، وDoubleMLDIDMulti.",
       objectives=("فهم ATT(g,t) عند التبني المتدرج.", "التمييز بين Panel وRepeated cross-sections.",
                   "تقدير DiD متعدد الفترات بـDML على بيانات تعليمية."),
       prereqs=("irm", "cross_validation"), difficulty="بحثي", minutes=55, lab="Staggered DiD Lab", dataset="panel",
       keywords=("difference in differences", "did", "panel", "staggered adoption", "att(g,t)", "never treated",
                 "anticipation", "parallel trends", "DoubleMLDID", "DoubleMLDIDMulti", "callaway sant'anna")),
    _M("dml_extensions", "app_pages/causal_ml/dml_extensions.py", "causal_ml", "امتدادات DML",
       "DML Extensions", ":material/extension:",
       "Cluster-robust، تحليل الحساسية، المعالجات المتعددة والمستمرة، الآثار الكمية، اختيار العينة، وRDD — كلها موثقة.",
       objectives=("إجراء تحليل حساسية وقراءة Robustness value.", "معرفة الامتدادات المدعومة حاليًا ومراجعها.",
                   "تجنب مصطلحات غير موثقة."),
       prereqs=("doubleml_package",), difficulty="بحثي", minutes=45, lab="Sensitivity Lab",
       keywords=("sensitivity analysis", "cluster robust", "multiway clustering", "continuous treatment",
                 "quantile treatment effect", "pq", "qte", "lpq", "cvar", "sample selection", "ssm", "rdd", "apo")),
    _M("dml_monte_carlo", "app_pages/causal_ml/dml_monte_carlo.py", "causal_ml", "مختبر DML الرئيسي",
       "DML Monte Carlo Lab", ":material/science:",
       "DGP اصطناعي بأثر حقيقي معروف: n وp وقوة الإرباك واللاخطية والضجيج والتداخل والمتعلم والطيات؛ ساذج مقابل DML.",
       objectives=("مقارنة الانحدار الساذج والمرن دون Cross-fitting وDML.", "قياس التحيز والتغطية بالمحاكاة.",
                   "فهم متى ينجح DML ومتى يتعثر."),
       prereqs=("plr", "dml_learners"), difficulty="بحثي", minutes=45, kind="lab", lab="DML Monte Carlo Lab",
       dataset="dml_nonlinear",
       keywords=("monte carlo", "simulation", "coverage", "bias", "dgp", "true effect", "naive", "محاكاة")),

    # ================================================================= modern
    _M("modern_topics", "app_pages/modern/modern_topics.py", "modern", "موضوعات حديثة في تعلّم الآلة",
       "Semi-supervised, Active, Online & Transfer Learning", ":material/new_releases:",
       "Semi-supervised (Self-training/Label spreading)، Active learning، Online/partial_fit، Concept drift، Transfer وSelf-supervised كمفاهيم.",
       objectives=("تطبيق Self-training على بيانات قليلة التسمية.", "محاكاة Active learning بعدم اليقين.",
                   "التدريب التزايدي بـpartial_fit."),
       prereqs=("logistic_regression", "cross_validation"), difficulty="متقدم", minutes=45, lab="Active Learning Lab",
       keywords=("semi-supervised", "self-training", "label spreading", "active learning", "online learning",
                 "partial_fit", "incremental", "transfer learning", "self-supervised", "concept drift")),
    _M("time_series_ml", "app_pages/modern/time_series_ml.py", "modern", "تعلّم الآلة للسلاسل الزمنية",
       "Time-Series ML", ":material/timeline:",
       "خصائص Lag وRolling والموسمية، Walk-forward validation، TimeSeriesSplit مع gap، والتسرب الزمني.",
       objectives=("بناء خصائص زمنية دون تسرب.", "تقييم بـWalk-forward.", "مقارنة نموذج شجري بـNaive forecast."),
       prereqs=("cross_validation", "leakage"), difficulty="متقدم", minutes=45, lab="Walk-forward Lab",
       dataset="timeseries",
       keywords=("time series", "lag features", "rolling", "seasonality", "walk-forward", "TimeSeriesSplit", "gap",
                 "forecasting", "temporal leakage", "سلاسل زمنية")),
    _M("text_ml", "app_pages/modern/text_ml.py", "modern", "تعلّم الآلة للنصوص", "Text ML",
       ":material/article:",
       "Bag of Words وTF-IDF وN-grams مع Naive Bayes وLogistic وLinear SVM، والتضمينات وتشابه جيب التمام كمفاهيم.",
       objectives=("بناء Pipeline نصي كامل.", "مقارنة المصنفات الخطية على TF-IDF.", "فهم التضمينات والتشابه."),
       prereqs=("naive_bayes", "pipelines"), difficulty="متوسط", minutes=40, lab="Text Classifier Lab", dataset="text",
       keywords=("text", "bag of words", "tf-idf", "TfidfVectorizer", "n-grams", "embeddings", "cosine similarity",
                 "nlp", "نص")),
    _M("rl_bridge", "app_pages/modern/rl_bridge.py", "modern", "جسر التعلّم المعزز", "Reinforcement Learning Bridge",
       ":material/sports_esports:",
       "الوكيل والبيئة والحالة والفعل والمكافأة والسياسة والعائد والاستكشاف/الاستغلال وMDP وQ-learning مع Gridworld.",
       objectives=("تعريف مكونات MDP.", "تشغيل Q-learning على Gridworld.", "فهم مقايضة الاستكشاف والاستغلال."),
       prereqs=("probability",), difficulty="متوسط", minutes=40, lab="Gridworld Q-learning Lab",
       keywords=("reinforcement learning", "agent", "environment", "reward", "policy", "mdp", "q-learning",
                 "epsilon greedy", "bandit", "معزز")),
    _M("dl_bridge", "app_pages/modern/dl_bridge.py", "modern", "جسر التعلّم العميق", "Deep Learning Bridge",
       ":material/neurology:",
       "Perceptron وMLP والطبقات المخفية والتنشيط والتمرير الأمامي وBackpropagation والـEpoch والـBatch.",
       objectives=("تنفيذ تمرير أمامي لشبكة صغيرة.", "فهم Backpropagation كقاعدة سلسلة.",
                   "تدريب MLPClassifier ورؤية حدّ القرار."),
       prereqs=("gradient_descent", "logistic_regression"), difficulty="متوسط", minutes=40, lab="MLP Lab", dataset="moons",
       keywords=("deep learning", "perceptron", "mlp", "neural network", "activation", "relu", "backpropagation",
                 "epoch", "batch", "MLPClassifier", "عميق")),

    # ============================================================= production
    _M("production_ml", "app_pages/production/production_ml.py", "production", "تعلّم الآلة في الإنتاج",
       "Production ML Systems", ":material/factory:",
       "النموذج جزء صغير من النظام: الـArtifact، الـPipeline، التدريب الثابت والديناميكي، الاستدلال الدفعي والفوري، الخدمة، والتراجع.",
       objectives=("رسم مكونات نظام ML إنتاجي.", "مقارنة Batch وOnline inference.",
                   "فهم مخاطر تسلسل النماذج (pickle)."),
       prereqs=("pipelines", "classification_metrics"), difficulty="متوسط", minutes=40,
       keywords=("production", "model artifact", "serving", "batch inference", "online inference", "rollback",
                 "logging", "pickle", "skops", "onnx", "إنتاج")),
    _M("mlops", "app_pages/production/mlops.py", "production", "مدخل عملي إلى MLOps", "MLOps",
       ":material/settings_suggest:",
       "تتبع التجارب وسجل النماذج والتحقق من البيانات والنماذج وCI/CD والنشر والمراقبة والنَّسب وإعادة الإنتاج وMLflow.",
       objectives=("فهم مستويات نضج MLOps.", "تسجيل تجربة وإصدار نموذج.", "تصميم فحوص CI للنموذج."),
       prereqs=("production_ml",), difficulty="متوسط", minutes=35,
       keywords=("mlops", "experiment tracking", "model registry", "mlflow", "ci/cd", "lineage", "deployment")),
    _M("drift", "app_pages/production/drift.py", "production", "الانجراف ومراقبة النماذج", "Drift & Monitoring",
       ":material/monitoring:",
       "Data drift وLabel drift وConcept drift وPerformance drift مع محاكي انجراف تفاعلي وPSI وKS.",
       objectives=("التمييز بين أنواع الانجراف الأربعة.", "قياس الانجراف بـPSI وKS.",
                   "تصميم سياسة إعادة التدريب."),
       prereqs=("production_ml",), difficulty="متقدم", minutes=40, lab="Drift Lab",
       keywords=("drift", "data drift", "covariate shift", "label shift", "concept drift", "psi", "ks test",
                 "monitoring", "retraining", "انجراف")),
    _M("fairness", "app_pages/production/fairness.py", "production", "العدالة وتعلّم الآلة المسؤول",
       "Fairness & Responsible ML", ":material/diversity_3:",
       "تحيز التمثيل والقياس والتسمية، أداء المجموعات الفرعية، Demographic parity وEqual opportunity، المقايضات، الخصوصية.",
       objectives=("حساب مقاييس العدالة الأساسية.", "فهم استحالة إرضاء كل المقاييس معًا.",
                   "تطبيق Data minimization وModel cards."),
       prereqs=("classification_metrics",), difficulty="متقدم", minutes=40, lab="Fairness Audit Lab",
       keywords=("fairness", "bias", "demographic parity", "equal opportunity", "equalized odds", "subgroup",
                 "privacy", "model card", "عدالة")),
    _M("reproducibility", "app_pages/production/reproducibility.py", "production", "قابلية إعادة الإنتاج وسجل التجارب",
       "Reproducibility & Experiment Log", ":material/history:",
       "البذور والإصدارات ونسخة البيانات واستراتيجية التقسيم والمعاملات، مع سجل تجارب قابل للتصدير.",
       objectives=("تثبيت كل مصادر العشوائية.", "توثيق التجربة بالكامل.", "تصدير سجل تجارب قابل للمراجعة."),
       prereqs=("pipelines",), minutes=30, lab="Experiment Log",
       keywords=("reproducibility", "random_state", "seed", "versions", "experiment log", "environment")),

    # ================================================================== labs
    _M("algorithm_selector", "app_pages/labs/algorithm_selector.py", "labs", "مساعد اختيار الخوارزمية",
       "Algorithm Selector", ":material/assistant_direction:",
       "أجب عن 12 سؤالًا (المهمة، الحجم، الخصائص، الفئات، التفسير، الزمن...) لتحصل على مرشحين مع المزايا والعيوب.",
       prereqs=("task_types",), minutes=15, kind="lab", lab="Algorithm Selector",
       keywords=("algorithm selection", "decision support", "which algorithm", "اختيار")),
    _M("algorithm_explorer", "app_pages/labs/algorithm_explorer.py", "labs", "مستكشف الخوارزميات",
       "Algorithm Explorer", ":material/travel_explore:",
       "ابحث وصفِّ الخوارزميات حسب النوع والخطية والمعلمية والقياس ودعم الفئات والقيم المفقودة والتفسير.",
       minutes=15, kind="lab", lab="Algorithm Explorer", tracked=False,
       keywords=("algorithm explorer", "filter", "matrix", "مستكشف")),
    _M("parameter_playground", "app_pages/labs/parameter_playground.py", "labs", "ساحة المعاملات",
       "Parameter Playground", ":material/sliders:",
       "اختر أي خوارزمية وغيّر معاملاتها لترى حدّ القرار ودرجة التدريب والتحقق والزمن والتعقيد مباشرة.",
       prereqs=("classification_setup",), difficulty="متوسط", minutes=25, kind="lab", lab="Parameter Playground",
       dataset="moons",
       keywords=("playground", "decision boundary", "hyperparameters", "train score", "validation score", "ساحة")),
    _M("model_comparison", "app_pages/labs/model_comparison.py", "labs", "مختبر مقارنة النماذج",
       "Model Comparison Lab", ":material/leaderboard:",
       "قارن عدة نماذج على نفس الطيات مع فترات عدم اليقين والزمن، دون إعلان فائز مطلق.",
       prereqs=("cross_validation",), difficulty="متوسط", minutes=25, kind="lab", lab="Model Comparison Lab",
       dataset="classification",
       keywords=("model comparison", "cross_validate", "leaderboard", "paired", "مقارنة")),

    # ============================================================== projects
    _M("projects_hub", "app_pages/projects/projects_hub.py", "projects", "المشاريع التطبيقية", "End-to-End Projects",
       ":material/work:",
       "عشرة مشاريع كاملة: انحدار، تصنيف ثنائي، غير متوازن، مقارنة التعزيز، تجزئة، شذوذ، نصوص، سلاسل زمنية، DML، وPanel DiD.",
       prereqs=("pipelines", "cross_validation", "classification_metrics"), difficulty="متقدم", minutes=180,
       kind="project",
       keywords=("projects", "end to end", "case study", "مشاريع")),
    _M("capstone_predictive", "app_pages/projects/capstone_predictive.py", "projects", "المشروع النهائي: التنبؤي",
       "Capstone A — Predictive ML", ":material/workspace_premium:",
       "13 مرحلة من المشكلة إلى التقرير النهائي: الجاهزية، التقسيم، Baseline، Pipeline، المرشحون، HPO، العتبة، تحليل الأخطاء.",
       prereqs=("projects_hub", "bayesian_optimization", "calibration"), difficulty="متقدم", minutes=180, kind="project",
       dataset="mixed",
       keywords=("capstone", "final project", "report", "error analysis", "نهائي")),
    _M("capstone_dml", "app_pages/projects/capstone_dml.py", "projects", "المشروع النهائي: السببي/DML",
       "Capstone B — Causal / DML", ":material/workspace_premium:",
       "11 مرحلة من السؤال السببي إلى التقرير: المعالجة، النتيجة، المتغيرات، الافتراضات، المتعلمون، Cross-fitting، الاستدلال، الحساسية.",
       prereqs=("dml_extensions", "dml_monte_carlo"), difficulty="بحثي", minutes=180, kind="project",
       dataset="causal",
       keywords=("capstone", "causal", "dml", "report", "sensitivity")),

    # ============================================================= resources
    _M("search", "app_pages/resources/search.py", "resources", "البحث", "Search", ":material/search:",
       "ابحث في الدروس والخوارزميات والمعاملات والصيغ والمسرد والمختبرات.", kind="resource", tracked=False,
       keywords=("search", "بحث")),
    _M("glossary", "app_pages/resources/glossary.py", "resources", "المسرد", "Glossary", ":material/book:",
       "مسرد عربي/إنجليزي قابل للبحث.", kind="resource", tracked=False,
       keywords=("glossary", "terms", "مسرد", "مصطلحات")),
    _M("cheat_sheets", "app_pages/resources/cheat_sheets.py", "resources", "أوراق المراجعة",
       "Cheat Sheets", ":material/receipt_long:",
       "اختيار الخوارزمية، متطلبات القياس، المقاييس، المقسّمات، معاملات الأشجار والتعزيز، HPO، وسير عمل DML.",
       kind="resource", tracked=False, keywords=("cheat sheet", "summary", "مراجعة")),
    _M("comparisons", "app_pages/resources/comparisons.py", "resources", "جداول المقارنة", "Comparison Tables",
       ":material/table_view:",
       "Ridge/Lasso/EN، Logistic/LDA/NB، kNN/SVM، Tree/RF، Bagging/Boosting، XGB/LGBM/CatBoost، وCV مقابل Cross-fitting.",
       kind="resource", tracked=False, keywords=("comparison", "versus", "vs", "مقارنة")),
    _M("references", "app_pages/resources/references.py", "resources", "المراجع", "References",
       ":material/library_books:",
       "المراجع العلمية بمعرّفات DOI متحقَّق منها، والوثائق الرسمية بالإصدارات وتاريخ التحقق.", kind="resource",
       tracked=False, keywords=("references", "doi", "sources", "papers", "مراجع")),
    _M("progress", "app_pages/resources/progress.py", "resources", "تقدّمي", "My Progress",
       ":material/trending_up:",
       "الوحدات المكتملة ونتائج الاختبارات والمختبرات والمفضلة، مع تصدير واستيراد التقدم.",
       kind="resource", tracked=False, keywords=("progress", "bookmarks", "تقدم", "مفضلة")),
    _M("about", "app_pages/resources/about.py", "resources", "عن المنصة", "About", ":material/info:",
       "عن المنصة والمطوّر والمنهجية والبيئة التقنية والإصدارات المتحقَّق منها.", kind="resource", tracked=False,
       keywords=("about", "author", "versions", "عن")),
)

_BY_ID: dict[str, Module] = {m.id: m for m in MODULES}


def get_module(module_id: str) -> Module:
    """Return a module by id, raising a clear error for typos."""
    try:
        return _BY_ID[module_id]
    except KeyError as exc:  # pragma: no cover - developer error
        raise KeyError(f"Unknown module id: {module_id!r}") from exc


def modules_in_group(group: str) -> list[Module]:
    return [m for m in MODULES if m.group == group]


def tracked_modules() -> list[Module]:
    return [m for m in MODULES if m.tracked]


def next_module(module_id: str) -> Module | None:
    """The next tracked module in curriculum order (skips resources)."""
    ids = [m.id for m in MODULES if m.tracked]
    if module_id not in ids:
        return None
    i = ids.index(module_id)
    return _BY_ID[ids[i + 1]] if i + 1 < len(ids) else None


# The main roadmap of section 9: (English, Arabic, module it links to)
ROADMAP: tuple[tuple[str, str, str], ...] = (
    ("Data Ready", "بيانات جاهزة", "ml_readiness"),
    ("Problem Definition", "تعريف المسألة", "task_types"),
    ("Statistical Learning", "التعلّم الإحصائي", "statistical_learning"),
    ("Feature Matrix", "مصفوفة الخصائص", "feature_matrix"),
    ("Baseline", "خط الأساس", "baselines"),
    ("Algorithm", "الخوارزمية", "linear_regression"),
    ("Loss", "الخسارة", "loss_functions"),
    ("Optimization", "التحسين", "gradient_descent"),
    ("Validation", "التحقق", "cross_validation"),
    ("Hyperparameter Tuning", "ضبط المعاملات", "hpo_foundations"),
    ("Evaluation", "التقييم", "classification_metrics"),
    ("Interpretation", "التفسير", "model_inspection"),
    ("Deployment", "النشر", "production_ml"),
    ("Monitoring", "المراقبة", "drift"),
)

LEARNING_PATHS: dict[str, dict] = {
    "regression": {
        "title": "مسار الانحدار · Regression",
        "desc": "من المربعات الصغرى إلى التنظيم والنماذج المتينة والتعزيز، مع مقاييس الانحدار وفترات التنبؤ.",
        "modules": ("feature_matrix", "linear_regression", "polynomial_regression", "regularization",
                    "robust_regression", "regression_metrics", "hist_gradient_boosting", "conformal_prediction"),
    },
    "classification": {
        "title": "مسار التصنيف · Classification",
        "desc": "من اللوجستي إلى SVM، ثم المقاييس والعتبة والمعايرة وعدم التوازن.",
        "modules": ("classification_setup", "logistic_regression", "naive_bayes", "lda_qda", "knn", "svm",
                    "classification_metrics", "threshold_tuning", "calibration", "imbalanced", "imb_metrics",
                    "imb_cost_sensitive"),
    },
    "imbalanced": {
        "title": "مسار التصنيف غير المتوازن · Imbalanced Classification",
        "desc": "من طبيعة عدم التوازن ومقاييسه إلى التكلفة وإعادة العيّنة والتجميعات المتوازنة والمعايرة ومنهجية كاملة.",
        "modules": ("classification_metrics", "threshold_tuning", "imbalanced", "imb_nature", "imb_metrics",
                    "imb_cost_sensitive", "imb_oversampling", "imb_undersampling", "imb_ensembles",
                    "imb_probabilities", "imb_multiclass_extreme", "imb_workflow"),
    },
    "breiman": {
        "title": "مسار فلسفة بريمان · Breiman's Philosophy",
        "desc": "الثقافتان، دروس Rashomon وOccam وBellman، ثم الأدوات التي بناها: الأشجار والتجميع والغابات، وصولًا إلى DML.",
        "modules": ("breiman_two_cultures", "breiman_three_lessons", "breiman_legacy", "decision_trees",
                    "ensemble_learning", "random_forest", "prediction_vs_causality", "dml_core"),
    },
    "trees": {
        "title": "مسار الأشجار والتجميعات · Trees & Ensembles",
        "desc": "من شجرة واحدة إلى الغابات والتعزيز والمكتبات الحديثة ومقارنتها.",
        "modules": ("decision_trees", "ensemble_learning", "random_forest", "boosting", "hist_gradient_boosting",
                    "xgboost", "lightgbm", "catboost", "boosting_comparison"),
    },
    "unsupervised": {
        "title": "مسار التعلّم غير الموجّه · Unsupervised",
        "desc": "التجميع بأنواعه، تقليل الأبعاد، واكتشاف الشذوذ.",
        "modules": ("kmeans", "hierarchical", "dbscan", "gmm", "pca", "manifold", "anomaly_detection"),
    },
    "optimization_hpo": {
        "title": "مسار التحسين وضبط المعاملات · Optimization & HPO",
        "desc": "دوال الخسارة، التحسين التدرجي والمتقدم، ثم البحث في فضاء المعاملات الفائقة.",
        "modules": ("loss_functions", "optimization_intro", "gradient_descent", "advanced_optimizers",
                    "cross_validation", "hpo_foundations", "bayesian_optimization"),
    },
    "causal": {
        "title": "مسار Causal ML وDML",
        "desc": "من النتائج الكامنة إلى التعامد وCross-fitting وPLR/PLIV/IRM/IIVM والآثار غير المتجانسة وDiD.",
        "modules": ("prediction_vs_causality", "causal_foundations", "dml_core", "neyman_orthogonality",
                    "cross_fitting", "plr", "pliv", "irm", "iivm", "dml_learners", "hte", "doubleml_package",
                    "panel_did", "dml_extensions", "dml_monte_carlo"),
    },
    "production": {
        "title": "مسار الإنتاج · Production ML",
        "desc": "من الـPipeline إلى النشر والمراقبة والانجراف والعدالة وإعادة الإنتاج.",
        "modules": ("pipelines", "production_ml", "mlops", "drift", "fairness", "reproducibility"),
    },
}
