"""Regenerate the registry-derived documentation.

    python scripts/build_docs.py

Writes docs/curriculum.md, docs/datasets.md, docs/algorithm_matrix.md,
docs/hyperparameters.md and docs/references.md from the single sources of
truth (core/curriculum.py, utils/datasets.py, content/*.py), so the docs can
never drift from the app. Hand-written docs (architecture, research notes,
research matrix, deployment) are not touched.
"""

from __future__ import annotations

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from config import APP_AUTHOR_EN, APP_NAME_EN, VERIFIED_ON  # noqa: E402
from content.algorithm_metadata import ALGORITHMS  # noqa: E402
from content.hyperparameters import CHECKED, HYPERPARAMETERS, VERIFIED_VERSIONS  # noqa: E402
from content.references import OFFICIAL_DOCS, REFERENCES  # noqa: E402
from core.curriculum import GROUPS, LEARNING_PATHS, MODULES, ROADMAP  # noqa: E402
from utils.datasets import DATASET_INFO  # noqa: E402

HEADER = f"<!-- generated by scripts/build_docs.py — do not edit by hand -->\n*{APP_NAME_EN} · {APP_AUTHOR_EN}*\n\n"


def _cell(v) -> str:
    return str(v).replace("|", "\\|").replace("\n", " ")


def write(name: str, text: str) -> None:
    path = os.path.join(ROOT, "docs", name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(HEADER + text)
    print("wrote", path)


def curriculum() -> str:
    out = ["# Curriculum", "", f"{len(MODULES)} pages in {len(GROUPS)} groups; "
           f"{sum(1 for m in MODULES if m.tracked)} tracked modules; {sum(1 for m in MODULES if m.lab)} with labs.", "",
           "## Roadmap", "", " → ".join(f"{en}" for en, _, _ in ROADMAP), ""]
    for g, label in GROUPS.items():
        mods = [m for m in MODULES if m.group == g]
        out += [f"## {label}", "", "| id | title | difficulty | min | lab | prerequisites |", "|---|---|---|---|---|---|"]
        for m in mods:
            out.append(f"| `{m.id}` | {m.title_ar} · {_cell(m.title_en)} | {m.difficulty} | {m.minutes} | {_cell(m.lab) or '—'} | "
                       f"{', '.join(m.prereqs) or '—'} |")
        out.append("")
    out += ["## Learning paths", ""]
    for p in LEARNING_PATHS.values():
        out += [f"### {p['title']}", "", p["desc"], "", " → ".join(f"`{m}`" for m in p["modules"]), ""]
    return "\n".join(out)


def datasets() -> str:
    out = ["# Datasets", "", "All datasets are synthetic and generated deterministically (seed in config.py); no data files ship with the app.", ""]
    for name, d in DATASET_INFO.items():
        out += [f"## `{name}` — {d.title}", "", f"- **Task:** {d.task} · **target:** `{d.target}`", f"- **Purpose:** {d.purpose}",
                f"- **Design:** {d.design}"]
        if d.truth:
            out.append(f"- **Ground truth:** `{d.truth}`")
        out += ["- **Variables:** " + "; ".join(f"`{k}` {v}" for k, v in d.variables.items()), ""]
    return "\n".join(out)


def algorithm_matrix() -> str:
    cols = ["algorithm", "estimator", "tasks", "linear", "parametric", "scaling", "categorical native", "missing native",
            "interpretability", "probabilistic", "online", "ensemble", "module"]
    out = ["# Algorithm matrix", "", "| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for a in ALGORITHMS:
        vals = [a.name, f"`{a.estimator}`", ", ".join(a.tasks), a.linear, a.parametric, a.scaling, a.categorical_native, a.missing_native,
                a.interpretability, a.probabilistic, a.online, a.ensemble, f"`{a.module}`"]
        out.append("| " + " | ".join(_cell(v) for v in vals) + " |")
    return "\n".join(out) + "\n"


def hyperparameters() -> str:
    out = ["# Hyperparameters", "", f"Defaults read from the installed libraries on {CHECKED} and re-checked by `tests/test_hyperparameters.py`.", "",
           "Verified versions: " + ", ".join(f"{k} {v}" for k, v in VERIFIED_VERSIONS.items()), "",
           "| library | estimator | parameter | default | allowed | meaning | source |", "|---|---|---|---|---|---|---|"]
    for h in HYPERPARAMETERS:
        default = repr(h.default) + (f" → {h.resolved}" if h.resolved else "")
        out.append(f"| {h.library} | `{h.algo}` | `{h.parameter}` | `{_cell(default)}` | {_cell(h.allowed)} | {_cell(h.meaning)} | "
                   f"[docs]({h.url}) |")
    return "\n".join(out) + "\n"


def references() -> str:
    out = ["# References", "", f"Every DOI resolved on doi.org and matched on Crossref; every arXiv id matched on arxiv.org; every URL returned "
           f"HTTP 200 — verified {VERIFIED_ON}.", ""]
    out += [f"- {r.citation} [{r.link}]({r.url})" for r in REFERENCES]
    out += ["", "## Official documentation consulted", "", "| documentation | version verified | url |", "|---|---|---|"]
    out += [f"| {n} | {v} | {u} |" for n, v, u in OFFICIAL_DOCS]
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    write("curriculum.md", curriculum())
    write("datasets.md", datasets())
    write("algorithm_matrix.md", algorithm_matrix())
    write("hyperparameters.md", hyperparameters())
    write("references.md", references())
