"""Quizzes: imbalanced classification track (the overview module 'imbalanced' lives in evaluation.py)."""

QUIZZES: dict[str, list[dict]] = {
    "imb_nature": [
        {"q": "3000 حالة منها 150 موجبة. IR = ؟", "type": "mcq", "options": ["0.05", "19", "20", "150"], "answer": 1,
         "explain": "2850 / 150 = 19."},
        {"q": "مع π = 0.01، المصنف الأمثل لـAccuracy يتنبأ بموجب فقط إذا كانت f₁(x)/f₀(x) ≥ :", "type": "mcq",
         "options": ["1", "0.01", "99", "0.5"], "answer": 2, "explain": "(1 − π)/π = 0.99/0.01 = 99."},
        {"q": "مجموعتا بيانات بانتشار 1%: الأولى 10 ملايين صف والثانية 2000 صف. الفرق الجوهري:", "type": "scenario",
         "options": ["لا فرق", "الندرة المطلقة: 100,000 موجب مقابل 20", "الأولى أصعب", "الانتشار مختلف"], "answer": 1,
         "explain": "عدد الموجبات المطلق يحدد ما يمكن تعلّمه."},
        {"q": "في مختبر الهندسة، زيادة المسافة بين الفئتين مع ثبات النسبة:", "type": "mcq",
         "options": ["لا تغير شيئًا", "تحسّن Recall بقوة: الصعوبة من التداخل لا من النسبة وحدها", "تسوء النتائج", "تغير IR"],
         "answer": 1, "explain": "التداخل مصدر رئيسي للصعوبة."},
    ],
    "imb_metrics": [
        {"q": "مصنّف عشوائي على بيانات انتشارها 2% يحقق PR-AUC تقريبًا:", "type": "mcq", "options": ["0.5", "0.02", "0", "1"],
         "answer": 1, "explain": "خط أساس PR هو الانتشار."},
        {"q": "مع انخفاض الانتشار وثبات قدرة الفصل:", "type": "mcq",
         "options": ["ROC-AUC وPR-AUC ينخفضان معًا", "ROC-AUC ثابت تقريبًا وPR-AUC ينخفض", "PR-AUC ثابت وROC-AUC ينخفض",
                     "كلاهما ثابت"], "answer": 1, "explain": "FPR لا يرى العدد المطلق للإنذارات الكاذبة؛ Precision يراه."},
        {"q": "TP = 30، FN = 20، FP = 70، TN = 880. أيهما أعلى؟", "type": "mcq",
         "options": ["MCC", "Accuracy", "متساويان", "غير محدد"], "answer": 1, "explain": "Accuracy = 0.91 بينما MCC ≈ 0.38."},
        {"q": "تفويت المريض أسوأ بكثير من إنذار كاذب. أي F-beta؟", "type": "method", "options": ["F0.5", "F1", "F2", "لا شيء"],
         "answer": 2, "explain": "β > 1 يعطي Recall وزنًا أكبر."},
        {"q": "فرق PR-AUC بين نموذجين 0.02 وعرض فترة Bootstrap 0.15. الاستنتاج:", "type": "scenario",
         "options": ["الأول أفضل قطعًا", "الفرق ضمن الضجيج؛ لا دليل على تفوق", "الثاني أفضل", "زِد العتبة"], "answer": 1,
         "explain": "مع موجبات قليلة يجب النظر إلى عدم اليقين."},
    ],
    "imb_cost_sensitive": [
        {"q": "C_FP = 2، C_FN = 18 (C_TP = C_TN = 0). العتبة المثلى على احتمالات معايرة:", "type": "mcq",
         "options": ["0.9", "0.1", "0.5", "0.18"], "answer": 1, "explain": "2 / (2 + 18) = 0.1."},
        {"q": "class_weight='balanced' في LogisticRegression يعادل تقريبًا:", "type": "mcq",
         "options": ["إضافة معلومات جديدة", "إزاحة الحد الثابت بـlog(w₁/w₀) (تغيير الأولوية)", "معايرة الاحتمالات",
                     "حذف الأغلبية"], "answer": 1, "explain": "خسارة موزونة = أولوية مختلفة = عتبة مختلفة."},
        {"q": "لماذا لا تُطبَّق t* = C_FP/(C_FP + C_FN) مباشرة على احتمالات نموذج دُرّب بـSMOTE؟", "type": "mcq",
         "options": ["لأن SMOTE بطيء", "لأن احتمالاته لم تعد معايرة للانتشار الحقيقي", "لأن الصيغة خاطئة", "يمكن تطبيقها"],
         "answer": 1, "explain": "صحّح الاحتمالات أو اضبط العتبة تجريبيًا."},
        {"q": "Focal loss مع γ = 0 وα = None يساوي:", "type": "mcq", "options": ["Hinge loss", "Log loss", "MSE", "صفر"],
         "answer": 1, "explain": "(1 − p_t)^0 = 1."},
        {"q": "تكلفة تفويت الاحتيال = مبلغ المعاملة. الأداة الأنسب:", "type": "method",
         "options": ["class_weight", "sample_weight لكل صف", "SMOTE", "RandomUnderSampler"], "answer": 1,
         "explain": "التكلفة فردية لا فئوية."},
    ],
    "imb_oversampling": [
        {"q": "أين يولّد SMOTE النقاط الجديدة؟", "type": "mcq",
         "options": ["نسخ مطابقة", "على القطع بين مثال أقلية وأحد جيرانه من الأقلية", "عشوائيًا في الفضاء", "في مركز الأغلبية"],
         "answer": 1, "explain": "x_new = x_i + λ(x_zi − x_i)."},
        {"q": "Borderline-SMOTE يولّد من الأمثلة التي:", "type": "mcq",
         "options": ["كل جيرانها من الأقلية", "نصف جيرانها أو أكثر (وليس كلهم) من الأغلبية", "كل جيرانها من الأغلبية",
                     "بعيدة عن الحد"], "answer": 1, "explain": "مجموعة DANGER: m/2 ≤ m' < m."},
        {"q": "بيانات فيها عمود city فئوي وأعمدة عددية. أي Sampler؟", "type": "method",
         "options": ["SMOTE على One-hot", "SMOTENC", "ADASYN", "SVMSMOTE"], "answer": 1,
         "explain": "SMOTENC يحافظ على قيم فئوية صالحة."},
        {"q": "لماذا يجب استخدام imblearn.pipeline لا sklearn.pipeline مع SMOTE؟", "type": "code",
         "options": ["أسرع", "لأنه يستدعي fit_resample على التدريب ويتخطى الـSampler عند التنبؤ", "لا فرق", "للرسوم"],
         "answer": 1, "explain": "sklearn.pipeline لا يعرف fit_resample."},
        {"q": "ADASYN حساس خصوصًا لـ:", "type": "mcq", "options": ["عدد الأعمدة", "ضجيج التسميات قرب الحد", "القياس", "الذاكرة"],
         "answer": 1, "explain": "يولّد أكثر حول الأمثلة «الصعبة» — وقد تكون ضجيجًا."},
    ],
    "imb_undersampling": [
        {"q": "Tomek link هو:", "type": "mcq",
         "options": ["أي زوج متشابه", "زوج من فئتين مختلفتين كل منهما أقرب جار للآخر", "مركز عنقود", "مثال شاذ"], "answer": 1,
         "explain": "يشير إلى حد أو ضجيج."},
        {"q": "صح أم خطأ: TomekLinks يعطي توازنًا 1:1.", "type": "tf", "options": ["صح", "خطأ"], "answer": 1,
         "explain": "طريقة تنظيف تحذف بضعة أمثلة فقط."},
        {"q": "ClusterCentroids:", "type": "mcq",
         "options": ["يحذف عشوائيًا", "يستبدل الأغلبية بمراكز K-Means", "يولّد أقلية", "ينظف الحد"], "answer": 1,
         "explain": "توليد نماذج أولية."},
        {"q": "SMOTEENN =", "type": "mcq", "options": ["SMOTE ثم ENN للتنظيف", "ENN فقط", "Tomek ثم SMOTE", "تجميع"], "answer": 0,
         "explain": "Oversampling ثم تنظيف منطقة التداخل."},
    ],
    "imb_ensembles": [
        {"q": "القيمة الافتراضية لـbootstrap في BalancedRandomForestClassifier (imbalanced-learn 0.14.2):", "type": "hyper",
         "options": ["True", "False", "None", "'auto'"], "answer": 1,
         "explain": "False منذ 0.13، مع replacement=True وsampling_strategy='all'."},
        {"q": "EasyEnsembleClassifier يدرّب على كل عيّنة متوازنة:", "type": "mcq",
         "options": ["شجرة واحدة", "AdaBoost كاملًا", "Logistic", "kNN"], "answer": 1, "explain": "ولذلك هو مكلف."},
        {"q": "أي خط أساس يجب أن يتفوق عليه أي تجميع متوازن؟", "type": "method",
         "options": ["DummyClassifier فقط", "نموذج قوي عادي مع عتبة مضبوطة بالتحقق", "شجرة بعمق 1", "لا شيء"], "answer": 1,
         "explain": "المقارنة عند 0.5 فقط غير منصفة."},
        {"q": "أي تجميعين يقبلان NaN في الإصدار المختبر؟", "type": "mcq",
         "options": ["EasyEnsemble وRUSBoost", "BalancedRandomForest وBalancedBagging (بالشجرة الافتراضية)", "كلها", "لا شيء"],
         "answer": 1, "explain": "AdaBoost لا يقبل NaN."},
    ],
    "imb_probabilities": [
        {"q": "نموذج دُرّب على 50/50 أعطى p_s = 0.5 والانتشار الحقيقي 5%. الاحتمال المصحح ≈", "type": "mcq",
         "options": ["0.5", "0.05", "0.95", "0.25"], "answer": 1,
         "explain": "p = 0.5·0.1 / (0.5·0.1 + 0.5·1.9) = 0.05."},
        {"q": "تصحيح الأولوية يغيّر ROC-AUC؟", "type": "tf", "options": ["نعم", "لا"], "answer": 1,
         "explain": "دالة رتيبة لا تغيّر الترتيب."},
        {"q": "خوارزمية EM لـSaerens et al. تفترض:", "type": "mcq",
         "options": ["Concept drift", "Label shift: P(x|y) ثابت ويتغير الانتشار فقط", "لا افتراضات", "بيانات معلَّمة"],
         "answer": 1, "explain": "وتحتاج احتمالات معايرة في التدريب."},
        {"q": "لماذا التصحيح تقريبي فقط بعد SMOTE؟", "type": "mcq",
         "options": ["SMOTE يغير P(x|y) بتوليد x جديدة", "SMOTE يحذف الأقلية", "لأنه بطيء", "ليس تقريبيًا"], "answer": 0,
         "explain": "بخلاف RandomUnderSampler الذي يحفظ P(x|y)."},
    ],
    "imb_multiclass_extreme": [
        {"q": "لتقييم فئة نادرة في مسألة 3 فئات:", "type": "mcq",
         "options": ["Weighted-F1", "Macro-F1 وRecall لكل فئة", "Accuracy", "Micro-F1"], "answer": 1,
         "explain": "Macro يعطي كل فئة وزنًا متساويًا."},
        {"q": "SMOTE(sampling_strategy={1: 600, 2: 600}) يعني:", "type": "code",
         "options": ["حذف 600 من كل فئة", "زيادة الفئتين 1 و2 إلى 600 صف لكل منهما في التدريب", "600 نقطة إجمالًا", "خطأ"],
         "answer": 1, "explain": "قاموس = العدد المستهدف لكل فئة."},
        {"q": "20 موجبًا في 4000 حالة و5 طيات. أهم احتياط:", "type": "method",
         "options": ["KFold عادي", "Stratified + Repeated CV والنظر إلى تشتت المقياس", "Test صغير جدًا", "SMOTE قبل CV"],
         "answer": 1, "explain": "4 موجبات لكل طية ⇒ تقلب كبير."},
        {"q": "متى يكون كشف الشذوذ بديلًا معقولًا؟", "type": "scenario",
         "options": ["حين تكون الموجبات كثيرة", "حين تكون الموجبات نادرة جدًا ومختلفة عن الأغلبية وقد تظهر أنماط جديدة",
                     "دائمًا", "أبدًا"], "answer": 1, "explain": "بشرط التحقق من أن «الشاذ» هو المهم."},
    ],
    "imb_workflow": [
        {"q": "الخطوة الأولى في المنهجية:", "type": "mcq",
         "options": ["SMOTE", "تعريف القرار ومصفوفة التكلفة", "اختيار XGBoost", "ضبط المعاملات"], "answer": 1,
         "explain": "التكلفة تحدد المقياس والعتبة."},
        {"q": "لماذا تُقيَّم كل التركيبات على الطيات نفسها؟", "type": "mcq",
         "options": ["للسرعة", "لتصبح الفروق مقترنة وقابلة للمقارنة", "لا يهم", "لتقليل الذاكرة"], "answer": 1,
         "explain": "يُزال تباين التقسيم من المقارنة."},
        {"q": "تركيبة أعطت أعلى Recall لكن mean p = 0.40 مع انتشار 0.05. ماذا يعني ذلك؟", "type": "scenario",
         "options": ["احتمالات ممتازة", "الاحتمالات مبالغ فيها (غير معايرة)", "Overfitting", "لا شيء"], "answer": 1,
         "explain": "الموازنة رفعت الاحتمالات؛ لا تُقرأ كمخاطر."},
    ],
}
