"""Quizzes: supervised learning (linear models, NB, LDA/QDA, kNN, SVM)."""

QUIZZES: dict[str, list[dict]] = {
    "linear_regression": [
        {"q": "لماذا مجموع بواقي OLS مع حد ثابت يساوي صفرًا؟", "type": "mcq",
         "options": ["صدفة", "لأن البواقي عمودية على عمود الواحدات (Xᵀe = 0)", "لأن البيانات مركزية", "ليس صحيحًا"], "answer": 1,
         "explain": "شرط الأمثلية Xᵀ(y − Xβ̂) = 0 يتضمن عمود الواحدات."},
        {"q": "أي افتراض ضروري للاستدلال السببي لا للتنبؤ؟", "type": "mcq",
         "options": ["طبيعية البواقي", "تجانس التباين", "Exogeneity: E[ε | X] = 0", "n > p"], "answer": 2,
         "explain": "التنبؤ الترابطي لا يحتاجه؛ تفسير β كأثر سببي يحتاجه."},
        {"q": "نقطة بعيدة جدًا في x وشاذة في y: ما مقياس تأثيرها؟", "type": "chart",
         "options": ["R²", "Cook's distance", "p-value", "VIF"], "answer": 1, "explain": "يجمع الرافعة وحجم الباقي."},
        {"q": "ماذا يقول Frisch–Waugh–Lovell؟", "type": "mcq",
         "options": ["R² يزيد مع p", "معامل x₁ = انحدار بواقي y على بواقي x₁ بعد إزالة أثر البقية", "OLS غير متحيز دائمًا",
                     "القياس لا يغير المعاملات"], "answer": 1, "explain": "الفكرة التي يعممها DML بـML وCross-fitting."},
    ],
    "polynomial_regression": [
        {"q": "PolynomialFeatures + LinearRegression نموذج:", "type": "mcq",
         "options": ["غير خطي في المعاملات", "خطي في المعاملات وغير خطي في x", "شجري", "غير معلمي"], "answer": 1,
         "explain": "نغيّر الأساسات ونبقي OLS."},
        {"q": "لماذا تتأرجح كثيرات الحدود العالية عند الأطراف؟", "type": "mcq",
         "options": ["خطأ برمجي", "لأنها عالمية: كل معامل يؤثر في كل مكان (Runge)", "لأن n كبير", "بسبب القياس"], "answer": 1,
         "explain": "Splines المحلية أكثر استقرارًا."},
        {"q": "كيف تختار الدرجة؟", "type": "hyper", "options": ["أعلى R² تدريب", "CV", "دائمًا 3", "على Test"], "answer": 1,
         "explain": "الدرجة معامل فائق."},
    ],
    "regularization": [
        {"q": "لماذا يُصفِّر Lasso معاملات بالضبط وRidge لا؟", "type": "mcq",
         "options": ["Lasso أسرع", "زوايا قيد L1 على المحاور", "Ridge غير محدب", "Ridge لا يستخدم alpha"], "answer": 1,
         "explain": "أول تماس بين القطع الناقص والماسة كثيرًا ما يكون عند زاوية."},
        {"q": "خاصيتان متطابقتا الأثر ومترابطتان بقوة. أي نموذج يوزع الوزن بينهما؟", "type": "method",
         "options": ["Lasso", "Ridge / Elastic Net", "OLS", "لا أحد"], "answer": 1, "explain": "L2 يفضّل توزيع الوزن."},
        {"q": "في مسار Lasso، عند زيادة α:", "type": "chart",
         "options": ["تدخل خصائص أكثر", "تخرج الخصائص تدريجيًا حتى تصبح كلها صفرًا", "لا يتغير شيء", "تزداد المعاملات"],
         "answer": 1, "explain": "عقوبة أقوى ⇒ ندرة أكبر."},
        {"q": "ما الخطأ في Lasso(alpha=0.1).fit(X_raw, y) مع أعمدة بوحدات مختلفة؟", "type": "code",
         "options": ["لا خطأ", "العقوبة غير متوازنة دون قياس", "Lasso لا يقبل DataFrame", "alpha صغير"], "answer": 1,
         "explain": "ضع StandardScaler في Pipeline."},
    ],
    "robust_regression": [
        {"q": "أي مقدِّر أضعف أمام نقاط الرافعة في x؟", "type": "mcq", "options": ["RANSAC", "Theil-Sen", "Huber", "كلها متساوية"],
         "answer": 2, "explain": "Huber يحد من البواقي الكبيرة لكن نقطة الرافعة تسحب الخط فيبدو باقيها صغيرًا."},
        {"q": "نقطة انهيار OLS:", "type": "mcq", "options": ["0% (نقطة واحدة تكفي)", "25%", "50%", "100%"], "answer": 0,
         "explain": "قيمة متطرفة واحدة يمكن أن تحرك التقدير بلا حدود."},
    ],
    "classification_setup": [
        {"q": "كم نموذجًا يدرّب OvO لـ10 فئات؟", "type": "mcq", "options": ["10", "45", "90", "1"], "answer": 1,
         "explain": "K(K−1)/2 = 45."},
        {"q": "decision_function لـSVM يعيد:", "type": "mcq",
         "options": ["احتمالات", "درجات موقعة غير محدودة", "فئات", "Log loss"], "answer": 1, "explain": "بُعد موقّع عن الحد."},
        {"q": "وسم صورة بعدة كائنات مسألة:", "type": "mcq", "options": ["Multiclass", "Multilabel", "Ordinal", "Binary"],
         "answer": 1, "explain": "مجموعة تسميات لكل ملاحظة."},
    ],
    "logistic_regression": [
        {"q": "β₁ = 0.7. زيادة x₁ بوحدة تضرب Odds بـ:", "type": "mcq", "options": ["0.7", "e^0.7 ≈ 2.01", "0.5", "1.7"],
         "answer": 1, "explain": "exp(β) = Odds ratio."},
        {"q": "في scikit-learn 1.9، كيف تحدد عقوبة L1؟", "type": "code",
         "options": ["penalty='l1'", "l1_ratio=1 مع solver='saga' أو 'liblinear'", "alpha=1", "C=0"], "answer": 1,
         "explain": "penalty مهجور منذ 1.8 ويُزال في 1.10."},
        {"q": "بيانات قابلة للفصل تمامًا وC = ∞. ماذا يحدث؟", "type": "scenario",
         "options": ["حل فريد منتهٍ", "المعاملات تتباعد نحو ∞ (عدم تقارب)", "Accuracy = 0.5", "لا شيء"], "answer": 1,
         "explain": "الإمكان يزداد دائمًا بتكبير المعاملات؛ التنظيم يحل ذلك."},
        {"q": "تقليل C:", "type": "hyper", "options": ["يضعف التنظيم", "يقوي التنظيم ويقرب الاحتمالات من 0.5", "لا أثر", "يغيّر solver"],
         "answer": 1, "explain": "C = مقلوب قوة التنظيم."},
    ],
    "naive_bayes": [
        {"q": "أي متغير يناسب عدّ الكلمات؟", "type": "method", "options": ["GaussianNB", "MultinomialNB", "QDA", "LinearRegression"],
         "answer": 1, "explain": "متعدد الحدود على العدّ."},
        {"q": "لماذا احتمالات NB مفرطة الثقة غالبًا؟", "type": "mcq",
         "options": ["بسبب alpha", "لأن الخصائص المترابطة تُحتسب كأدلة مستقلة", "لأنه خطي", "ليست كذلك"], "answer": 1,
         "explain": "كسر الاستقلال الشرطي يضاعف الأدلة المتكررة."},
        {"q": "alpha في MultinomialNB:", "type": "hyper", "options": ["معدل تعلّم", "تنعيم Laplace/Lidstone", "عتبة", "عدد الكلمات"],
         "answer": 1, "explain": "يمنع الاحتمالات الصفرية لكلمات لم تُرَ مع فئة."},
    ],
    "lda_qda": [
        {"q": "متى يكون حد التحليل التمييزي خطيًا؟", "type": "mcq",
         "options": ["دائمًا", "حين تتشارك الفئات مصفوفة التغاير (LDA)", "حين n كبير", "مع QDA"], "answer": 1,
         "explain": "الحد التربيعي يلغي نفسه مع Σ مشتركة."},
        {"q": "p = 50، n = 30 لكل فئة. أيهما أنسب؟", "type": "method",
         "options": ["QDA", "LDA مع shrinkage='auto'", "QDA بلا تنظيم", "kNN بـk=1"], "answer": 1,
         "explain": "QDA يقدّر تغايرًا لكل فئة (1275 معاملًا!)."},
        {"q": "أقصى عدد مكونات LDA لـ3 فئات:", "type": "mcq", "options": ["1", "2", "3", "p"], "answer": 1, "explain": "K − 1."},
    ],
    "knn": [
        {"q": "k = 1 يعطي دقة تدريب:", "type": "mcq", "options": ["50%", "100% (عدا التكرارات المتناقضة)", "0%", "غير محددة"],
         "answer": 1, "explain": "كل نقطة أقرب جيرانها نفسها."},
        {"q": "ماذا يحدث للحدود مع زيادة k؟", "type": "chart", "options": ["أكثر تعرجًا", "أنعم", "لا تتغير", "تختفي"], "answer": 1,
         "explain": "متوسط على جوار أكبر ⇒ تباين أقل وتحيز أعلى."},
        {"q": "لماذا القياس إلزامي؟", "type": "mcq", "options": ["للسرعة", "لأن المسافة تسيطر عليها الخاصية ذات المقياس الأكبر",
                                                             "لا يلزم", "للتنظيم"], "answer": 1,
         "explain": "المختبر أظهر فرقًا كبيرًا بعد ضرب خاصية واحدة في 1000."},
    ],
    "svm": [
        {"q": "أي النقاط تحدد حد SVM؟", "type": "mcq", "options": ["كل النقاط", "المتجهات الداعمة فقط", "المتوسطات", "الشواذ"],
         "answer": 1, "explain": "النقاط خارج الهامش لها αᵢ = 0."},
        {"q": "RBF مع gamma كبير جدًا يؤدي إلى:", "type": "hyper", "options": ["Underfitting", "Overfitting (جزر حول النقاط)",
                                                                              "حد خطي", "لا أثر"], "answer": 1,
         "explain": "تأثير كل نقطة محلي جدًا."},
        {"q": "كيف تحصل على احتمالات من SVC في scikit-learn 1.9+؟", "type": "code",
         "options": ["probability=True", "CalibratedClassifierCV(SVC(), ensemble=False)", "predict_proba مباشرة", "لا يمكن"],
         "answer": 1, "explain": "probability مهجور في 1.9 ويُزال في 1.11."},
        {"q": "مليون صف ونصوص متفرقة. أي تنفيذ؟", "type": "method", "options": ["SVC(kernel='rbf')", "LinearSVC أو SGDClassifier(hinge)",
                                                                                 "SVC(kernel='poly')", "QDA"], "answer": 1,
         "explain": "SVC بين O(n²) وO(n³)."},
    ],
}
