"""Quizzes: trees and ensembles."""

QUIZZES: dict[str, list[dict]] = {
    "decision_trees": [
        {"q": "Gini لعقدة فيها 80% فئة A و20% فئة B:", "type": "mcq", "options": ["0.2", "0.32", "0.5", "0.8"], "answer": 1,
         "explain": "1 − (0.8² + 0.2²) = 1 − 0.68 = 0.32."},
        {"q": "لماذا حدود الشجرة مستطيلة؟", "type": "mcq",
         "options": ["بسبب Gini", "لأن كل تقسيم يختبر خاصية واحدة مقابل عتبة", "بسبب القياس", "ليست كذلك"], "answer": 1,
         "explain": "تقسيمات محاذية للمحاور."},
        {"q": "زيادة ccp_alpha:", "type": "hyper", "options": ["شجرة أكبر", "شجرة أصغر (تقليم أكثر)", "لا أثر", "عمق أكبر"],
         "answer": 1, "explain": "ثمن أعلى لكل ورقة."},
        {"q": "صح أم خطأ: شجرة القرار في scikit-learn تحتاج StandardScaler.", "type": "tf", "options": ["صح", "خطأ"], "answer": 1,
         "explain": "العتبات لا تتأثر بالتحويلات الرتيبة."},
    ],
    "ensemble_learning": [
        {"q": "Var(average) = ρσ² + (1−ρ)σ²/B. ما الذي يحد فائدة إضافة نماذج؟", "type": "mcq",
         "options": ["B", "الارتباط ρ بين النماذج", "σ² فقط", "لا شيء"], "answer": 1, "explain": "ρσ² لا يزول مع B."},
        {"q": "Stacking دون تنبؤات خارج الطية يؤدي إلى:", "type": "mcq",
         "options": ["نتائج أدق", "نموذج فوقي يثق بتنبؤات تدريب متفائلة (تسرب)", "لا فرق", "خطأ برمجي"], "answer": 1,
         "explain": "النماذج الأساسية تبدو ممتازة على بيانات تدريبها."},
        {"q": "أي أسلوب يخفض التحيز أساسًا؟", "type": "method", "options": ["Bagging", "Boosting", "Voting", "Random subspace"],
         "answer": 1, "explain": "كل مرحلة تصحح أخطاء النموذج الحالي."},
    ],
    "random_forest": [
        {"q": "احتمال ألا يُسحب صف في عينة Bootstrap كبيرة ≈", "type": "mcq", "options": ["0%", "36.8%", "50%", "63.2%"], "answer": 1,
         "explain": "(1 − 1/n)ⁿ → e⁻¹."},
        {"q": "زيادة n_estimators في RF:", "type": "hyper", "options": ["تسبب Overfitting", "تثبّت التنبؤ دون Overfitting إضافي",
                                                                      "تزيد التحيز", "تلغي الحاجة للتحقق"], "answer": 1,
         "explain": "متوسط أشجار أكثر = تباين أقل حتى الاستقرار."},
        {"q": "في المختبر حصلت random_id على أهمية MDI ملحوظة. لماذا؟", "type": "chart",
         "options": ["إنها مفيدة فعلًا", "الأشجار العميقة تقسم عليها لحفظ التدريب؛ MDI يُحسب على التدريب", "خطأ", "OOB"],
         "answer": 1, "explain": "Permutation على بيانات منفصلة تكشف أنها بلا قيمة."},
        {"q": "max_features='sqrt' هدفه:", "type": "mcq", "options": ["السرعة فقط", "تقليل ارتباط الأشجار", "تقليل العمق", "القياس"],
         "answer": 1, "explain": "يمنع كل الأشجار من اختيار الخاصية الأقوى نفسها."},
    ],
    "boosting": [
        {"q": "في Gradient boosting بخسارة MSE، تتعلم كل شجرة:", "type": "mcq",
         "options": ["y", "البواقي y − F(x)", "الأوزان", "sign(y)"], "answer": 1, "explain": "التدرج السالب لـ½(y − F)² هو y − F."},
        {"q": "خفض learning_rate من 0.3 إلى 0.05 يتطلب:", "type": "hyper", "options": ["أشجارًا أقل", "أشجارًا أكثر", "عمقًا أكبر", "لا شيء"],
         "answer": 1, "explain": "خطوات أصغر ⇒ مراحل أكثر."},
        {"q": "صح أم خطأ: زيادة المراحل في Boosting آمنة كزيادة الأشجار في RF.", "type": "tf", "options": ["صح", "خطأ"], "answer": 1,
         "explain": "Boosting يفرط في الملاءمة مع مراحل زائدة."},
    ],
    "hist_gradient_boosting": [
        {"q": "ما الذي يجعل HGB سريعًا؟", "type": "mcq", "options": ["GPU", "Binning إلى ≤255 صندوقًا", "أشجار أقل", "لا يستخدم تدرجات"],
         "answer": 1, "explain": "البحث عن التقسيم على الصناديق لا على كل القيم."},
        {"q": "متى يتفعل early_stopping='auto'؟", "type": "mcq", "options": ["دائمًا", "إذا n > 10000", "أبدًا", "مع الفئات فقط"], "answer": 1,
         "explain": "متحقَّق من التوثيق والسلوك في 1.9.1."},
        {"q": "كيف يعالج HGB القيم المفقودة؟", "type": "mcq", "options": ["يحذف الصفوف", "يعوّض بالمتوسط", "يتعلم إلى أي ابن ترسل NaN عند كل تقسيم",
                                                                         "يرمي خطأ"], "answer": 2, "explain": "صندوق مخصص للمفقود."},
    ],
    "xgboost": [
        {"q": "في XGBoost، وزن الورقة الأمثل:", "type": "mcq", "options": ["متوسط y", "−G/(H + λ)", "G/H", "λ"], "answer": 1,
         "explain": "من التقريب التربيعي للهدف المنظَّم."},
        {"q": "gamma في XGBoost:", "type": "hyper", "options": ["معدل التعلم", "أقل كسب مطلوب لقبول التقسيم", "L2 على الأوراق", "عدد الأشجار"],
         "answer": 1, "explain": "alias: min_split_loss."},
        {"q": "القيمة الفعلية الافتراضية لـlearning_rate في XGBClassifier:", "type": "mcq", "options": ["0.1", "0.3", "0.01", "1.0"],
         "answer": 1, "explain": "الـwrapper يمرر None؛ config الـbooster: eta = 0.3."},
    ],
    "lightgbm": [
        {"q": "LightGBM ينمّي الأشجار:", "type": "mcq", "options": ["Level-wise", "Leaf-wise", "Symmetric", "عشوائيًا"], "answer": 1,
         "explain": "يوسّع الورقة ذات أكبر كسب."},
        {"q": "subsample=0.8 دون subsample_freq:", "type": "hyper", "options": ["Bagging 80%", "لا أثر (freq = 0 يعطّل Bagging)", "خطأ", "20%"],
         "answer": 1, "explain": "bagging_freq يجب أن يكون > 0."},
        {"q": "في LightGBM 4.7، كيف تمرر بيانات التحقق في fit؟", "type": "code",
         "options": ["eval_set فقط", "eval_X وeval_y (eval_set مهجور)", "validation_data", "X_val"], "answer": 1,
         "explain": "متحقَّق من تحذير LGBMDeprecationWarning في 4.7.0."},
    ],
    "catboost": [
        {"q": "لماذا Target statistics مرتّبة؟", "type": "mcq",
         "options": ["للسرعة", "حتى لا يُستخدم هدف الصف نفسه في ترميزه (تسرب)", "للمعايرة", "للذاكرة"], "answer": 1,
         "explain": "يُستخدم فقط الصفوف السابقة في تبديل عشوائي."},
        {"q": "الأشجار في CatBoost:", "type": "mcq", "options": ["Leaf-wise", "متناظرة (Oblivious)", "عميقة جدًا", "خطية"], "answer": 1,
         "explain": "التقسيم نفسه في كل مستوى."},
        {"q": "أفضل ممارسة مع فئة city ذات 40 قيمة:", "type": "method", "options": ["One-hot مسبق", "cat_features=['city']", "حذفها", "أرقام 0..39"],
         "answer": 1, "explain": "دع CatBoost يستخدم Ordered TS."},
    ],
    "boosting_comparison": [
        {"q": "مقارنة المكتبات بإعداداتها الافتراضية تقارن:", "type": "mcq",
         "options": ["الخوارزميات", "الإعدادات الافتراضية أساسًا", "السرعة فقط", "لا شيء"], "answer": 1,
         "explain": "الافتراضيات مختلفة جدًا (1000 تكرار مقابل 100...)."},
        {"q": "فرق AUC = 0.004 وSD عبر الطيات = 0.01. الاستنتاج:", "type": "scenario",
         "options": ["فائز واضح", "لا دليل على فرق", "الأدنى سيئ", "أعد على Test"], "answer": 1, "explain": "الفرق ضمن الضجيج."},
    ],
}
